import type { QmsInspectionStandard } from '@iaf/domain-types';
import { useAuthStore } from '@iaf/auth';
import { PermissionButton, QMS_PERMISSIONS } from '@iaf/permissions';
import { AppPageContainer } from '@iaf/ui-core';
import { Alert, App, Button, Card, Descriptions, Input, Modal, Space, Table, Tag, Timeline, Typography } from 'antd';
import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import { useNavigate, useParams } from 'react-router-dom';
import { qmsEngineeringApi } from './api';

type Action = 'submit-approval'|'approve'|'reject'|'release';

export const QmsInspectionStandardPage=()=>{
  const revisionId=Number(useParams().revisionId); const navigate=useNavigate(); const {message}=App.useApp(); const {t}=useTranslation(); const queryClient=useQueryClient();
  const principal=useAuthStore(state=>state.principal);
  const query=useQuery({queryKey:['qms-inspection-standard',revisionId],queryFn:()=>qmsEngineeringApi.getInspectionStandard(revisionId)});
  const [draft,setDraft]=useState<QmsInspectionStandard|null>(null); const [action,setAction]=useState<Action|null>(null); const [comment,setComment]=useState('');
  useEffect(()=>setDraft(query.data??null),[query.data]);
  const refresh=()=>queryClient.invalidateQueries({queryKey:['qms-inspection-standard',revisionId]});
  const updatePayload=()=>({version:draft!.version,reactionPlan:draft!.reactionPlan,items:draft!.items.map(x=>({id:x.id,requirement:x.requirement,supplierBatchSampling:x.supplierBatchSampling,supplierBatchMethod:x.supplierBatchMethod,supplierAnnualSampling:x.supplierAnnualSampling,supplierAnnualMethod:x.supplierAnnualMethod,remark:x.remark}))});
  const generate=useMutation({mutationFn:()=>qmsEngineeringApi.generateInspectionStandard(revisionId),onSuccess:async result=>{setDraft(result);queryClient.setQueryData(['qms-inspection-standard',revisionId],result);await refresh();message.success(t(draft?'qms.inspectionStandard.synchronized':'qms.inspectionStandard.generated'));}});
  const save=useMutation({mutationFn:()=>qmsEngineeringApi.updateInspectionStandard(revisionId,draft!.id,updatePayload()),onSuccess:async result=>{setDraft(result);queryClient.setQueryData(['qms-inspection-standard',revisionId],result);await refresh();message.success(t('qms.inspectionStandard.saved'));}});
  const act=useMutation({mutationFn:async()=>{if(action==='submit-approval'){const saved=await qmsEngineeringApi.updateInspectionStandard(revisionId,draft!.id,updatePayload());setDraft(saved);queryClient.setQueryData(['qms-inspection-standard',revisionId],saved);}return qmsEngineeringApi.actOnInspectionStandard(revisionId,draft!.id,action!,comment);},onSuccess:async result=>{setDraft(result);queryClient.setQueryData(['qms-inspection-standard',revisionId],result);setAction(null);setComment('');await refresh();message.success(t('qms.inspectionStandard.actionSuccess'));}});
  const editable=Boolean(draft&&['AI_GENERATED','DRAFT','REJECTED'].includes(draft.status));
  const cannotApproveOwn=Boolean(draft?.status==='APPROVING'&&draft.submittedBy===principal?.userId);
  const patchItem=(row:number,patch:Partial<QmsInspectionStandard['items'][number]>)=>setDraft(current=>current?{...current,items:current.items.map((item,index)=>index===row?{...item,...patch}:item)}:current);
  const field=(key:keyof QmsInspectionStandard['items'][number],value:string,row:number)=><Input aria-label={String(key)} disabled={!editable} value={value??''} onChange={event=>patchItem(row,{[key]:event.target.value})}/>;
  const actionButton=(name:Action,permission:string,label:string,danger=false,disabled=false)=><PermissionButton require={permission} danger={danger} disabled={disabled} onClick={()=>setAction(name)}>{label}</PermissionButton>;
  return <AppPageContainer title={t('qms.inspectionStandard.title')} extra={<Space wrap><Button onClick={()=>navigate(-1)}>{t('qms.inspectionStandard.back')}</Button>{draft&&<Button onClick={()=>navigate(`/qms/engineering/inspection-standards/${draft.id}/validation-plan`)}>{t('qms.validationPlan.title')}</Button>}{draft&&(editable||draft.status==='RELEASED')&&<PermissionButton require={QMS_PERMISSIONS.inspectionStandardEdit} loading={generate.isPending} disabled={save.isPending} onClick={()=>generate.mutate()}>{t('qms.inspectionStandard.sync')}</PermissionButton>}{draft&&editable&&<PermissionButton require={QMS_PERMISSIONS.inspectionStandardEdit} type="primary" loading={save.isPending} disabled={generate.isPending} onClick={()=>save.mutate()}>{t('qms.inspectionStandard.save')}</PermissionButton>}{draft&&editable&&actionButton('submit-approval',QMS_PERMISSIONS.inspectionStandardSubmit,t('qms.inspectionStandard.submit'))}{draft?.status==='APPROVING'&&draft.approvalStatus==='PENDING'&&<>{actionButton('approve',QMS_PERMISSIONS.inspectionStandardApprove,t('qms.inspectionStandard.approve'),false,cannotApproveOwn)}{actionButton('reject',QMS_PERMISSIONS.inspectionStandardApprove,t('qms.inspectionStandard.reject'),true,cannotApproveOwn)}</>}{draft?.status==='APPROVING'&&draft.approvalStatus==='APPROVED'&&actionButton('release',QMS_PERMISSIONS.inspectionStandardRelease,t('qms.inspectionStandard.release'))}</Space>}>
    {!draft?<Alert type="info" showIcon message={t('qms.inspectionStandard.empty')} description={t('qms.inspectionStandard.emptyHelp')} action={<PermissionButton require={QMS_PERMISSIONS.inspectionStandardEdit} type="primary" loading={generate.isPending} onClick={()=>generate.mutate()}>{t('qms.inspectionStandard.generate')}</PermissionButton>}/>:<>
      {!editable&&<Alert showIcon type="warning" message={t('qms.inspectionStandard.readOnly')} style={{marginBottom:16}}/>}
      {cannotApproveOwn&&<Alert showIcon type="info" message={t('qms.inspectionStandard.selfApprovalBlocked')} style={{marginBottom:16}}/>}
      {editable&&<Alert showIcon type="info" message={t('qms.inspectionStandard.syncHelp')} style={{marginBottom:16}}/>}
      <Card size="small"><Descriptions size="small" column={{xs:1,sm:2,lg:4}} items={[{key:'no',label:draft.standardNo,children:t('qms.inspectionStandard.version',{version:draft.documentVersion})},{key:'document',label:t('qms.inspectionStandard.documentStatus'),children:<Tag>{t(`qms.status.${draft.status}`,{defaultValue:draft.status})}</Tag>},{key:'approval',label:t('qms.inspectionStandard.approvalStatus'),children:<Tag>{t(`qms.status.${draft.approvalStatus}`,{defaultValue:draft.approvalStatus})}</Tag>},{key:'updated',label:'Updated',children:draft.updatedAt}]}/><Input.TextArea disabled={!editable} rows={2} value={draft.reactionPlan??''} placeholder={t('qms.inspectionStandard.reactionPlan')} onChange={e=>setDraft({...draft,reactionPlan:e.target.value})}/></Card>
      <Table style={{marginTop:16}} rowKey="id" pagination={false} scroll={{x:1400}} dataSource={draft.items} columns={[{title:t('qms.inspectionStandard.columns.sequence'),dataIndex:'sequenceNo',width:70},{title:t('qms.inspectionStandard.columns.category'),dataIndex:'category',width:100},{title:t('qms.inspectionStandard.columns.item'),dataIndex:'itemName',width:180},{title:t('qms.inspectionStandard.columns.requirement'),dataIndex:'requirement',width:220,render:(v:string,_x,ri)=>field('requirement',v,ri)},{title:t('qms.inspectionStandard.columns.special'),dataIndex:'specialCharacteristicCode',width:100},{title:t('qms.inspectionStandard.columns.batchSampling'),dataIndex:'supplierBatchSampling',width:140,render:(v:string,_x,ri)=>field('supplierBatchSampling',v,ri)},{title:t('qms.inspectionStandard.columns.batchMethod'),dataIndex:'supplierBatchMethod',width:180,render:(v:string,_x,ri)=>field('supplierBatchMethod',v,ri)},{title:t('qms.inspectionStandard.columns.annualSampling'),dataIndex:'supplierAnnualSampling',width:140,render:(v:string,_x,ri)=>field('supplierAnnualSampling',v,ri)},{title:t('qms.inspectionStandard.columns.annualMethod'),dataIndex:'supplierAnnualMethod',width:180,render:(v:string,_x,ri)=>field('supplierAnnualMethod',v,ri)},{title:t('qms.inspectionStandard.columns.remark'),dataIndex:'remark',width:180,render:(v:string,_x,ri)=>field('remark',v,ri)}]}/>
      <Card size="small" title={t('qms.inspectionStandard.history')} style={{marginTop:16}}>{draft.approvalActions.length?<Timeline items={draft.approvalActions.map(x=>({children:<Space direction="vertical" size={0}><Typography.Text strong>{x.action}</Typography.Text><Typography.Text type="secondary">{t('qms.inspectionStandard.actor',{id:x.actorId})} · {x.actedAt}</Typography.Text>{x.comment&&<Typography.Text>{x.comment}</Typography.Text>}</Space>}))}/>:<Typography.Text type="secondary">{t('qms.inspectionStandard.noHistory')}</Typography.Text>}</Card>
    </>}
    <Modal open={Boolean(action)} title={action?t(`qms.inspectionStandard.${action==='submit-approval'?'submit':action}`):''} confirmLoading={act.isPending} onCancel={()=>setAction(null)} onOk={()=>act.mutate()}><Input.TextArea autoFocus rows={4} maxLength={1000} showCount value={comment} placeholder={t('qms.inspectionStandard.actionComment')} onChange={e=>setComment(e.target.value)}/></Modal>
  </AppPageContainer>;
};
