import type { QmsValidationPlan } from '@iaf/domain-types';
import { PermissionButton,QMS_PERMISSIONS } from '@iaf/permissions';
import { AppPageContainer } from '@iaf/ui-core';
import { Alert,App,Button,Card,Checkbox,Descriptions,Input,InputNumber,Modal,Space,Table,Tag,Timeline,Typography } from 'antd';
import { useEffect,useState } from 'react';import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';import { useTranslation } from 'react-i18next';import { useNavigate,useParams } from 'react-router-dom';import { qmsEngineeringApi } from './api';
type Action='submit-approval'|'approve'|'reject'|'release';
export const QmsValidationPlanPage=()=>{const standardId=Number(useParams().inspectionStandardId);const navigate=useNavigate();const {message}=App.useApp();const {t}=useTranslation();const client=useQueryClient();const query=useQuery({queryKey:['qms-validation-plan',standardId],queryFn:()=>qmsEngineeringApi.getValidationPlan(standardId),enabled:Number.isFinite(standardId)&&standardId>0});const [draft,setDraft]=useState<QmsValidationPlan|null>(null);const [action,setAction]=useState<Action|null>(null);const [comment,setComment]=useState('');useEffect(()=>setDraft(query.data??null),[query.data]);const refresh=()=>client.invalidateQueries({queryKey:['qms-validation-plan',standardId]});
 const generate=useMutation({mutationFn:()=>qmsEngineeringApi.generateValidationPlan(standardId),onSuccess:async result=>{setDraft(result);client.setQueryData(['qms-validation-plan',standardId],result);await refresh();message.success(t('qms.validationPlan.generated'));}});
 const save=useMutation({mutationFn:()=>qmsEngineeringApi.updateValidationPlan(standardId,draft!.id,{version:draft!.version,supplierId:draft!.supplierId,items:draft!.items.map(x=>({id:x.id,methodAcceptanceCriteria:x.methodAcceptanceCriteria,laboratoryId:x.laboratoryId,dvRequired:x.dvRequired,pvRequired:x.pvRequired,typeRequired:x.typeRequired,batchRequired:x.batchRequired,quantity:x.quantity,startDate:x.startDate,endDate:x.endDate,equivalentInfo:x.equivalentInfo}))}),onSuccess:async()=>{await refresh();message.success(t('qms.validationPlan.saved'));}});
 const act=useMutation({mutationFn:()=>qmsEngineeringApi.actOnValidationPlan(standardId,draft!.id,action!,comment),onSuccess:async()=>{setAction(null);setComment('');await refresh();message.success(t('qms.validationPlan.actionSuccess'));}});const editable=Boolean(draft&&['AI_GENERATED','DRAFT','REJECTED'].includes(draft.status));const patch=(row:number,value:Partial<QmsValidationPlan['items'][number]>)=>setDraft(c=>c?{...c,items:c.items.map((x,i)=>i===row?{...x,...value}:x)}:c);const actionButton=(name:Action,permission:string,label:string,danger=false)=><PermissionButton require={permission} danger={danger} onClick={()=>setAction(name)}>{label}</PermissionButton>;
 return <AppPageContainer title={t('qms.validationPlan.title')} extra={<Space wrap><Button onClick={()=>navigate(-1)}>{t('common.actions.back')}</Button>{draft&&editable&&<PermissionButton require={QMS_PERMISSIONS.validationPlanEdit} type="primary" loading={save.isPending} onClick={()=>save.mutate()}>{t('common.actions.save')}</PermissionButton>}{draft&&editable&&actionButton('submit-approval',QMS_PERMISSIONS.validationPlanSubmit,t('qms.validationPlan.submit'))}{draft?.status==='APPROVING'&&draft.approvalStatus==='PENDING'&&<>{actionButton('approve',QMS_PERMISSIONS.validationPlanApprove,t('qms.validationPlan.approve'))}{actionButton('reject',QMS_PERMISSIONS.validationPlanApprove,t('qms.validationPlan.reject'),true)}</>}{draft?.status==='APPROVING'&&draft.approvalStatus==='APPROVED'&&actionButton('release',QMS_PERMISSIONS.validationPlanRelease,t('qms.validationPlan.release'))}</Space>}>
  {!draft?<Alert type="info" showIcon message={t('qms.validationPlan.empty')} description={t('qms.validationPlan.emptyHelp')} action={<PermissionButton require={QMS_PERMISSIONS.validationPlanEdit} type="primary" loading={generate.isPending} onClick={()=>generate.mutate()}>{t('qms.validationPlan.generate')}</PermissionButton>}/>:<>{!editable&&<Alert type="warning" showIcon message={t('qms.validationPlan.readOnly')} style={{marginBottom:16}}/>}<Card size="small"><Descriptions size="small" column={{xs:1,sm:2,lg:4}} items={[{key:'no',label:t('qms.validationPlan.planNo'),children:draft.planNo},{key:'version',label:t('qms.validationPlan.version'),children:draft.documentVersion},{key:'status',label:t('qms.validationPlan.documentStatus'),children:<Tag>{t(`qms.status.${draft.status}`,{defaultValue:draft.status})}</Tag>},{key:'approval',label:t('qms.validationPlan.approvalStatus'),children:<Tag>{t(`qms.status.${draft.approvalStatus}`,{defaultValue:draft.approvalStatus})}</Tag>}]}/><InputNumber aria-label={t('qms.validationPlan.supplierId')} disabled={!editable} min={1} value={draft.supplierId} placeholder={t('qms.validationPlan.supplierId')} onChange={v=>setDraft({...draft,supplierId:v})}/></Card>
  <Table style={{marginTop:16}} rowKey="id" pagination={false} scroll={{x:1800}} dataSource={draft.items} columns={[{title:t('qms.validationPlan.columns.sequence'),dataIndex:'sequenceNo',width:70},{title:t('qms.validationPlan.columns.testItem'),dataIndex:'testItem',width:180},{title:t('qms.validationPlan.columns.standard'),dataIndex:'standardSource',width:200},{title:t('qms.validationPlan.columns.criteria'),dataIndex:'methodAcceptanceCriteria',width:240,render:(v:string,_x,ri)=><Input disabled={!editable} value={v??''} onChange={e=>patch(ri,{methodAcceptanceCriteria:e.target.value})}/>},{title:t('qms.validationPlan.columns.lab'),dataIndex:'laboratoryId',width:120,render:(v:number|null,_x,ri)=><InputNumber disabled={!editable} min={1} value={v} onChange={n=>patch(ri,{laboratoryId:n})}/>},{title:'DV',dataIndex:'dvRequired',width:65,render:(v:boolean,_x,ri)=><Checkbox disabled={!editable} checked={v} onChange={e=>patch(ri,{dvRequired:e.target.checked})}/>},{title:'PV',dataIndex:'pvRequired',width:65,render:(v:boolean,_x,ri)=><Checkbox disabled={!editable} checked={v} onChange={e=>patch(ri,{pvRequired:e.target.checked})}/>},{title:t('qms.validationPlan.columns.type'),dataIndex:'typeRequired',width:80,render:(v:boolean,_x,ri)=><Checkbox disabled={!editable} checked={v} onChange={e=>patch(ri,{typeRequired:e.target.checked})}/>},{title:t('qms.validationPlan.columns.batch'),dataIndex:'batchRequired',width:80,render:(v:boolean,_x,ri)=><Checkbox disabled={!editable} checked={v} onChange={e=>patch(ri,{batchRequired:e.target.checked})}/>},{title:t('qms.validationPlan.columns.quantity'),dataIndex:'quantity',width:100,render:(v:number|null,_x,ri)=><InputNumber disabled={!editable} min={1} value={v} onChange={n=>patch(ri,{quantity:n})}/>},{title:t('qms.validationPlan.columns.start'),dataIndex:'startDate',width:150,render:(v:string|null,_x,ri)=><Input type="date" disabled={!editable} value={v??''} onChange={e=>patch(ri,{startDate:e.target.value||null})}/>},{title:t('qms.validationPlan.columns.end'),dataIndex:'endDate',width:150,render:(v:string|null,_x,ri)=><Input type="date" disabled={!editable} value={v??''} onChange={e=>patch(ri,{endDate:e.target.value||null})}/>},{title:t('qms.validationPlan.columns.equivalent'),dataIndex:'equivalentInfo',width:220,render:(v:string|null,_x,ri)=><Input disabled={!editable} value={v??''} onChange={e=>patch(ri,{equivalentInfo:e.target.value})}/>}]} />
  <Card size="small" title={t('qms.validationPlan.history')} style={{marginTop:16}}>{draft.approvalActions.length?<Timeline items={draft.approvalActions.map(x=>({children:<Space direction="vertical" size={0}><Typography.Text strong>{x.action}</Typography.Text><Typography.Text type="secondary">{x.actorId} · {x.actedAt}</Typography.Text>{x.comment&&<Typography.Text>{x.comment}</Typography.Text>}</Space>}))}/>:<Typography.Text type="secondary">{t('qms.validationPlan.noHistory')}</Typography.Text>}</Card></>}
  <Modal open={Boolean(action)} title={action?t(`qms.validationPlan.${action==='submit-approval'?'submit':action}`):''} confirmLoading={act.isPending} onCancel={()=>setAction(null)} onOk={()=>act.mutate()}><Input.TextArea autoFocus rows={4} maxLength={1000} showCount value={comment} placeholder={t('qms.validationPlan.comment')} onChange={e=>setComment(e.target.value)}/></Modal>
 </AppPageContainer>;
};
