package com.company.iaf.qms.engineering.infrastructure.persistence;

import com.company.iaf.platform.core.security.RequiresPermission;
import com.company.iaf.platform.statemachine.application.*;
import com.company.iaf.platform.workflow.application.*;
import com.company.iaf.qms.engineering.application.QmsEngineeringErrorCode;
import com.company.iaf.qms.engineering.domain.model.InspectionStandardStatus;
import com.company.iaf.qms.engineering.domain.repository.*;
import com.company.iaf.qms.engineering.interfaces.dto.*;
import com.company.iaf.shared.exception.BusinessException;
import com.company.iaf.shared.security.SecurityContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.Timestamp;
import java.util.*;

@Service
public class InspectionStandardService {
    private static final String BUSINESS_TYPE="INSPECTION_STANDARD";
    private static final List<StateTransition<InspectionStandardStatus>> TRANSITIONS=List.of(
            new StateTransition<>(InspectionStandardStatus.AI_GENERATED,"submit",InspectionStandardStatus.APPROVING),
            new StateTransition<>(InspectionStandardStatus.DRAFT,"submit",InspectionStandardStatus.APPROVING),
            new StateTransition<>(InspectionStandardStatus.REJECTED,"submit",InspectionStandardStatus.APPROVING),
            new StateTransition<>(InspectionStandardStatus.APPROVING,"approve",InspectionStandardStatus.APPROVING),
            new StateTransition<>(InspectionStandardStatus.APPROVING,"reject",InspectionStandardStatus.REJECTED),
            new StateTransition<>(InspectionStandardStatus.APPROVING,"release",InspectionStandardStatus.RELEASED));
    private final JdbcTemplate jdbc; private final DrawingRevisionRepository revisions; private final QmsAuditTrail audit;
    private final StateMachineService states; private final ApprovalApplicationService approvals;
    public InspectionStandardService(JdbcTemplate j,DrawingRevisionRepository r,QmsAuditTrail a,StateMachineService s,ApprovalApplicationService p){jdbc=j;revisions=r;audit=a;states=s;approvals=p;}

    @RequiresPermission("qms:drawing-revision:view") @Transactional(readOnly=true)
    public InspectionStandardResponse get(long t,long o,long r){requireRevision(t,o,r);return find(t,o,r).orElse(null);}

    @RequiresPermission("qms:inspection-standard:edit") @Transactional
    public InspectionStandardResponse generate(long t,long o,long r){requireRevision(t,o,r);var old=find(t,o,r);if(old.isPresent())return old.get();var src=jdbc.queryForList("select q.*,d.drawing_no from qms_quality_characteristic q join qms_drawing_revision v on v.tenant_id=q.tenant_id and v.id=q.drawing_revision_id join qms_drawing d on d.tenant_id=v.tenant_id and d.id=v.drawing_id where q.tenant_id=? and q.org_id=? and q.drawing_revision_id=? and q.review_status='CONFIRMED' and q.deleted=false and (q.inspection_dimension or q.mandatory_inspection) and not q.reference_dimension and not q.ideal_dimension order by q.id",t,o,r);if(src.isEmpty())throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_NO_ELIGIBLE_SOURCE);long actor=actor();var first=src.getFirst();Long id=jdbc.queryForObject("insert into qms_inspection_standard(tenant_id,org_id,standard_no,part_id,drawing_revision_id,created_by,updated_by) values(?,?,?,?,?,?,?) returning id",Long.class,t,o,"IS-"+first.get("drawing_no")+"-1",first.get("part_id"),r,actor,actor);int seq=1;for(var x:src)jdbc.update("insert into qms_inspection_standard_item(tenant_id,org_id,inspection_standard_id,sequence_no,category,item_name,requirement,characteristic_id,nominal_value,lower_limit,upper_limit,special_characteristic_code,supplier_batch_sampling,supplier_batch_method,supplier_annual_sampling,supplier_annual_method,evidence_id,confidence,created_by,updated_by) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",t,o,id,seq++,category(String.valueOf(x.get("characteristic_type"))),x.get("name"),requirement(x),x.get("id"),x.get("nominal_value"),x.get("lower_limit"),x.get("upper_limit"),x.get("special_characteristic_code"),"每批","按图纸检验","每年一次","全尺寸检验",x.get("evidence_id"),x.get("confidence"),actor,actor);return audited(t,actor,"INSPECTION_STANDARD_DRAFT_GENERATED",id,find(t,o,r).orElseThrow());}

    @RequiresPermission("qms:inspection-standard:edit") @Transactional
    public InspectionStandardResponse update(long t,long o,long r,long id,InspectionStandardUpdateRequest q){var current=require(t,o,r,id);var state=status(current);if(state==InspectionStandardStatus.RELEASED||state==InspectionStandardStatus.APPROVING)throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_INVALID_STATE);long actor=actor();if(jdbc.update("update qms_inspection_standard set reaction_plan=?,status='DRAFT',approval_status='NOT_SUBMITTED',updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=? and version=? and deleted=false",q.reactionPlan(),actor,t,o,id,q.version())!=1)throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_CONFLICT);for(var i:q.items())if(jdbc.update("update qms_inspection_standard_item set requirement=?,supplier_batch_sampling=?,supplier_batch_method=?,supplier_annual_sampling=?,supplier_annual_method=?,remark=?,review_status='CONFIRMED',updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and inspection_standard_id=? and id=? and deleted=false",i.requirement(),i.supplierBatchSampling(),i.supplierBatchMethod(),i.supplierAnnualSampling(),i.supplierAnnualMethod(),i.remark(),actor,t,o,id,i.id())!=1)throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_CONFLICT);return audited(t,actor,"INSPECTION_STANDARD_DRAFT_UPDATED",id,find(t,o,r).orElseThrow());}

    @RequiresPermission("qms:inspection-standard:submit") @Transactional public InspectionStandardResponse submit(long t,long o,long r,long id,String comment){var current=require(t,o,r,id);transition(status(current),"submit");if(unresolved(t,o,id)>0)throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_RELEASE_BLOCKED);long actor=actor();try{approvals.submit(t,o,BUSINESS_TYPE,id,actor,comment);}catch(IllegalStateException e){throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_INVALID_STATE);}jdbc.update("update qms_inspection_standard set status='APPROVING',approval_status='PENDING',submitted_by=?,submitted_at=current_timestamp,updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=?",actor,actor,t,o,id);return audited(t,actor,"INSPECTION_STANDARD_SUBMITTED",id,find(t,o,r).orElseThrow());}
    @RequiresPermission("qms:inspection-standard:approve") @Transactional public InspectionStandardResponse approve(long t,long o,long r,long id,String comment){var current=require(t,o,r,id);transition(status(current),"approve");long actor=actor();try{approvals.approve(t,o,BUSINESS_TYPE,id,actor,comment);}catch(IllegalStateException e){throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_INVALID_STATE);}jdbc.update("update qms_inspection_standard set approval_status='APPROVED',approved_by=?,approved_at=current_timestamp,updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=?",actor,actor,t,o,id);return audited(t,actor,"INSPECTION_STANDARD_APPROVED",id,find(t,o,r).orElseThrow());}
    @RequiresPermission("qms:inspection-standard:approve") @Transactional public InspectionStandardResponse reject(long t,long o,long r,long id,String comment){var current=require(t,o,r,id);transition(status(current),"reject");long actor=actor();try{approvals.reject(t,o,BUSINESS_TYPE,id,actor,comment);}catch(IllegalStateException e){throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_INVALID_STATE);}jdbc.update("update qms_inspection_standard set status='REJECTED',approval_status='REJECTED',updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=?",actor,t,o,id);return audited(t,actor,"INSPECTION_STANDARD_REJECTED",id,find(t,o,r).orElseThrow());}
    @RequiresPermission("qms:inspection-standard:release") @Transactional public InspectionStandardResponse release(long t,long o,long r,long id,String comment){var current=require(t,o,r,id);transition(status(current),"release");if(!"APPROVED".equals(current.approvalStatus())||unresolved(t,o,id)>0)throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_RELEASE_BLOCKED);long actor=actor();jdbc.update("update qms_inspection_standard set status='RELEASED',released_by=?,released_at=current_timestamp,updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=?",actor,actor,t,o,id);return audited(t,actor,"INSPECTION_STANDARD_RELEASED",id,find(t,o,r).orElseThrow());}

    private InspectionStandardResponse require(long t,long o,long r,long id){return find(t,o,r).filter(x->x.id()==id).orElseThrow(()->error(QmsEngineeringErrorCode.INSPECTION_STANDARD_NOT_FOUND));}
    private void transition(InspectionStandardStatus current,String action){try{states.requireTransition(current,action,TRANSITIONS);}catch(IllegalStateException e){throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_INVALID_STATE);}}
    private int unresolved(long t,long o,long id){return Objects.requireNonNull(jdbc.queryForObject("select count(*) from qms_inspection_standard_item where tenant_id=? and org_id=? and inspection_standard_id=? and deleted=false and (review_status<>'CONFIRMED' or requirement is null or btrim(requirement)='')",Integer.class,t,o,id));}
    private Optional<InspectionStandardResponse> find(long t,long o,long r){var ss=jdbc.queryForList("select * from qms_inspection_standard where tenant_id=? and org_id=? and drawing_revision_id=? and deleted=false order by document_version desc limit 1",t,o,r);if(ss.isEmpty())return Optional.empty();var s=ss.getFirst();long id=(long)s.get("id");var items=jdbc.query("select * from qms_inspection_standard_item where tenant_id=? and org_id=? and inspection_standard_id=? and deleted=false order by sequence_no",(x,n)->new InspectionStandardResponse.Item(x.getLong("id"),x.getInt("sequence_no"),x.getString("category"),x.getString("item_name"),x.getString("requirement"),x.getLong("characteristic_id"),x.getBigDecimal("nominal_value"),x.getBigDecimal("lower_limit"),x.getBigDecimal("upper_limit"),x.getString("special_characteristic_code"),x.getString("supplier_batch_sampling"),x.getString("supplier_batch_method"),x.getString("supplier_annual_sampling"),x.getString("supplier_annual_method"),x.getString("remark"),x.getString("source_type"),(Long)x.getObject("evidence_id"),x.getBigDecimal("confidence"),x.getString("review_status")),t,o,id);var approval=approvals.findLatest(t,o,BUSINESS_TYPE,id);var actions=approval.map(a->a.actions().stream().map(x->new InspectionStandardResponse.ApprovalAction(x.action(),x.actorId(),x.comment(),x.actedAt())).toList()).orElse(List.of());return Optional.of(new InspectionStandardResponse(id,(String)s.get("standard_no"),(long)s.get("part_id"),r,(int)s.get("document_version"),(String)s.get("status"),(String)s.get("approval_status"),(String)s.get("source_type"),(String)s.get("reaction_plan"),(int)s.get("version"),time(s,"updated_at"),(Long)s.get("submitted_by"),time(s,"submitted_at"),(Long)s.get("approved_by"),time(s,"approved_at"),(Long)s.get("released_by"),time(s,"released_at"),actions,items));}
    private static java.time.LocalDateTime time(Map<String,Object>s,String key){var x=(Timestamp)s.get(key);return x==null?null:x.toLocalDateTime();}
    private InspectionStandardResponse audited(long t,long actor,String action,long id,InspectionStandardResponse result){audit.record(t,actor,action,"InspectionStandard",id,result);return result;}
    private void requireRevision(long t,long o,long r){if(revisions.findById(t,o,r).isEmpty())throw error(QmsEngineeringErrorCode.REVISION_NOT_FOUND);}private static InspectionStandardStatus status(InspectionStandardResponse x){return InspectionStandardStatus.valueOf(x.status());}private static long actor(){return SecurityContext.getUserId().orElse(0L);}private static BusinessException error(QmsEngineeringErrorCode c){return new BusinessException(c);}private static String category(String v){return switch(v){case"DIMENSION"->"DIMENSION";case"APPEARANCE"->"APPEARANCE";case"PERFORMANCE"->"PERFORMANCE";default->"OTHER";};}private static String requirement(Map<String,Object>x){return x.get("nominal_value")+(x.get("lower_limit")==null?"":" ("+x.get("lower_limit")+" ~ "+x.get("upper_limit")+")");}
}
