package com.company.iaf.qms.engineering.infrastructure.persistence;

import com.company.iaf.platform.core.security.RequiresPermission;
import com.company.iaf.platform.statemachine.application.*;
import com.company.iaf.platform.workflow.application.*;
import com.company.iaf.qms.engineering.application.QmsEngineeringErrorCode;
import com.company.iaf.qms.engineering.domain.model.ValidationPlanStatus;
import com.company.iaf.qms.engineering.domain.repository.QmsAuditTrail;
import com.company.iaf.qms.engineering.interfaces.dto.*;
import com.company.iaf.shared.exception.BusinessException;
import com.company.iaf.shared.security.SecurityContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.*;import java.time.*;import java.util.*;

@Service
public class ValidationPlanService {
 private static final String BUSINESS_TYPE="VALIDATION_PLAN";
 private static final List<StateTransition<ValidationPlanStatus>> TRANSITIONS=List.of(
  new StateTransition<>(ValidationPlanStatus.AI_GENERATED,"submit",ValidationPlanStatus.APPROVING),new StateTransition<>(ValidationPlanStatus.DRAFT,"submit",ValidationPlanStatus.APPROVING),new StateTransition<>(ValidationPlanStatus.REJECTED,"submit",ValidationPlanStatus.APPROVING),new StateTransition<>(ValidationPlanStatus.APPROVING,"approve",ValidationPlanStatus.APPROVING),new StateTransition<>(ValidationPlanStatus.APPROVING,"reject",ValidationPlanStatus.REJECTED),new StateTransition<>(ValidationPlanStatus.APPROVING,"release",ValidationPlanStatus.RELEASED));
 private final JdbcTemplate jdbc;private final QmsAuditTrail audit;private final StateMachineService states;private final ApprovalApplicationService approvals;
 public ValidationPlanService(JdbcTemplate jdbc,QmsAuditTrail audit,StateMachineService states,ApprovalApplicationService approvals){this.jdbc=jdbc;this.audit=audit;this.states=states;this.approvals=approvals;}

 @RequiresPermission("qms:drawing-revision:view") @Transactional(readOnly=true)
 public ValidationPlanResponse get(long t,long o,long standardId){requireSource(t,o,standardId);return find(t,o,standardId).orElse(null);}

 @RequiresPermission("qms:validation-plan:edit") @Transactional
 public ValidationPlanResponse generate(long t,long o,long standardId){var source=requireSource(t,o,standardId);if(!"RELEASED".equals(source.get("status")))throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_SOURCE_NOT_RELEASED);var old=find(t,o,standardId);if(old.isPresent())return old.get();var items=jdbc.queryForList("select * from qms_inspection_standard_item where tenant_id=? and org_id=? and inspection_standard_id=? and category='PERFORMANCE' and review_status='CONFIRMED' and deleted=false order by sequence_no",t,o,standardId);if(items.isEmpty())throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_NO_PERFORMANCE_SOURCE);long actor=actor();Long id=jdbc.queryForObject("insert into qms_validation_plan(tenant_id,org_id,plan_no,part_id,inspection_standard_id,drawing_revision_id,supplier_id,created_by,updated_by) values(?,?,?,?,?,?,?,?,?) returning id",Long.class,t,o,"VP-"+source.get("standard_no")+"-1",source.get("part_id"),standardId,source.get("drawing_revision_id"),source.get("supplier_id"),actor,actor);int seq=1;for(var x:items)jdbc.update("insert into qms_validation_plan_item(tenant_id,org_id,validation_plan_id,sequence_no,test_item,standard_source,method_acceptance_criteria,dv_required,pv_required,type_required,batch_required,source_inspection_item_id,source_characteristic_id,evidence_id,created_by,updated_by) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",t,o,id,seq++,x.get("item_name"),x.get("requirement"),x.get("requirement"),false,false,hasText(x.get("supplier_annual_sampling")),hasText(x.get("supplier_batch_sampling")),x.get("id"),x.get("characteristic_id"),x.get("evidence_id"),actor,actor);return audited(t,actor,"VALIDATION_PLAN_DRAFT_GENERATED",id,find(t,o,standardId).orElseThrow());}

 @RequiresPermission("qms:validation-plan:edit") @Transactional
 public ValidationPlanResponse update(long t,long o,long standardId,long id,ValidationPlanUpdateRequest q){var current=require(t,o,standardId,id);if(!editable(status(current)))throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_INVALID_STATE);long actor=actor();if(jdbc.update("update qms_validation_plan set supplier_id=?,status='DRAFT',approval_status='NOT_SUBMITTED',updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=? and version=? and deleted=false",q.supplierId(),actor,t,o,id,q.version())!=1)throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_CONFLICT);for(var i:q.items()){if(i.startDate()!=null&&i.endDate()!=null&&i.endDate().isBefore(i.startDate()))throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_CONFLICT);if(jdbc.update("update qms_validation_plan_item set method_acceptance_criteria=?,laboratory_id=?,dv_required=?,pv_required=?,type_required=?,batch_required=?,quantity=?,start_date=?,end_date=?,equivalent_info=?,review_status='CONFIRMED',updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and validation_plan_id=? and id=? and deleted=false",i.methodAcceptanceCriteria(),i.laboratoryId(),i.dvRequired(),i.pvRequired(),i.typeRequired(),i.batchRequired(),i.quantity(),i.startDate(),i.endDate(),i.equivalentInfo(),actor,t,o,id,i.id())!=1)throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_CONFLICT);}return audited(t,actor,"VALIDATION_PLAN_DRAFT_UPDATED",id,find(t,o,standardId).orElseThrow());}

 @RequiresPermission("qms:validation-plan:submit") @Transactional public ValidationPlanResponse submit(long t,long o,long s,long id,String comment){var c=require(t,o,s,id);transition(status(c),"submit");if(unresolved(t,o,id)>0)throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_RELEASE_BLOCKED);long a=actor();try{approvals.submit(t,o,BUSINESS_TYPE,id,a,comment);}catch(IllegalStateException e){throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_INVALID_STATE);}jdbc.update("update qms_validation_plan set status='APPROVING',approval_status='PENDING',submitted_by=?,submitted_at=current_timestamp,updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=?",a,a,t,o,id);return audited(t,a,"VALIDATION_PLAN_SUBMITTED",id,find(t,o,s).orElseThrow());}
 @RequiresPermission("qms:validation-plan:approve") @Transactional public ValidationPlanResponse approve(long t,long o,long s,long id,String comment){var c=require(t,o,s,id);transition(status(c),"approve");long a=actor();try{approvals.approve(t,o,BUSINESS_TYPE,id,a,comment);}catch(IllegalStateException e){throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_INVALID_STATE);}jdbc.update("update qms_validation_plan set approval_status='APPROVED',approved_by=?,approved_at=current_timestamp,updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=?",a,a,t,o,id);return audited(t,a,"VALIDATION_PLAN_APPROVED",id,find(t,o,s).orElseThrow());}
 @RequiresPermission("qms:validation-plan:approve") @Transactional public ValidationPlanResponse reject(long t,long o,long s,long id,String comment){var c=require(t,o,s,id);transition(status(c),"reject");long a=actor();try{approvals.reject(t,o,BUSINESS_TYPE,id,a,comment);}catch(IllegalStateException e){throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_INVALID_STATE);}jdbc.update("update qms_validation_plan set status='REJECTED',approval_status='REJECTED',updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=?",a,t,o,id);return audited(t,a,"VALIDATION_PLAN_REJECTED",id,find(t,o,s).orElseThrow());}
 @RequiresPermission("qms:validation-plan:release") @Transactional public ValidationPlanResponse release(long t,long o,long s,long id,String comment){var c=require(t,o,s,id);transition(status(c),"release");if(!"APPROVED".equals(c.approvalStatus())||unresolved(t,o,id)>0)throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_RELEASE_BLOCKED);long a=actor();jdbc.update("update qms_validation_plan set status='RELEASED',released_by=?,released_at=current_timestamp,updated_by=?,updated_at=current_timestamp,version=version+1 where tenant_id=? and org_id=? and id=?",a,a,t,o,id);return audited(t,a,"VALIDATION_PLAN_RELEASED",id,find(t,o,s).orElseThrow());}

 private Map<String,Object> requireSource(long t,long o,long id){var list=jdbc.queryForList("select s.*,p.supplier_id from qms_inspection_standard s join qms_part p on p.tenant_id=s.tenant_id and p.id=s.part_id where s.tenant_id=? and s.org_id=? and s.id=? and not s.deleted and not p.deleted",t,o,id);if(list.isEmpty())throw error(QmsEngineeringErrorCode.INSPECTION_STANDARD_NOT_FOUND);return list.getFirst();}
 private ValidationPlanResponse require(long t,long o,long s,long id){return find(t,o,s).filter(x->x.id()==id).orElseThrow(()->error(QmsEngineeringErrorCode.VALIDATION_PLAN_NOT_FOUND));}
 private Optional<ValidationPlanResponse> find(long t,long o,long s){var plans=jdbc.queryForList("select * from qms_validation_plan where tenant_id=? and org_id=? and inspection_standard_id=? and deleted=false order by document_version desc limit 1",t,o,s);if(plans.isEmpty())return Optional.empty();var p=plans.getFirst();long id=((Number)p.get("id")).longValue();var items=jdbc.query("select * from qms_validation_plan_item where tenant_id=? and org_id=? and validation_plan_id=? and not deleted order by sequence_no",(r,n)->new ValidationPlanResponse.Item(r.getLong("id"),r.getInt("sequence_no"),r.getString("test_item"),r.getString("standard_source"),r.getString("method_acceptance_criteria"),(Long)r.getObject("laboratory_id"),r.getBoolean("dv_required"),r.getBoolean("pv_required"),r.getBoolean("type_required"),r.getBoolean("batch_required"),(Integer)r.getObject("quantity"),r.getObject("start_date",LocalDate.class),r.getObject("end_date",LocalDate.class),r.getString("equivalent_info"),r.getLong("source_inspection_item_id"),r.getLong("source_characteristic_id"),(Long)r.getObject("evidence_id"),r.getString("review_status")),t,o,id);var approval=approvals.findLatest(t,o,BUSINESS_TYPE,id);var actions=approval.map(x->x.actions().stream().map(a->new ValidationPlanResponse.ApprovalAction(a.action(),a.actorId(),a.comment(),a.actedAt())).toList()).orElse(List.of());return Optional.of(new ValidationPlanResponse(id,(String)p.get("plan_no"),((Number)p.get("part_id")).longValue(),s,((Number)p.get("drawing_revision_id")).longValue(),((Number)p.get("document_version")).intValue(),(String)p.get("status"),(String)p.get("approval_status"),(Long)p.get("supplier_id"),((Number)p.get("version")).intValue(),time(p,"updated_at"),(Long)p.get("submitted_by"),time(p,"submitted_at"),(Long)p.get("approved_by"),time(p,"approved_at"),(Long)p.get("released_by"),time(p,"released_at"),actions,items));}
 private int unresolved(long t,long o,long id){return Objects.requireNonNull(jdbc.queryForObject("select count(*) from qms_validation_plan_item where tenant_id=? and org_id=? and validation_plan_id=? and not deleted and (review_status<>'CONFIRMED' or method_acceptance_criteria is null or btrim(method_acceptance_criteria)='')",Integer.class,t,o,id));}
 private void transition(ValidationPlanStatus current,String action){try{states.requireTransition(current,action,TRANSITIONS);}catch(IllegalStateException e){throw error(QmsEngineeringErrorCode.VALIDATION_PLAN_INVALID_STATE);}}
 private ValidationPlanResponse audited(long t,long actor,String action,long id,ValidationPlanResponse result){audit.record(t,actor,action,"ValidationPlan",id,result);return result;}
 private static boolean hasText(Object x){return x!=null&&!String.valueOf(x).isBlank();}private static boolean editable(ValidationPlanStatus s){return s==ValidationPlanStatus.AI_GENERATED||s==ValidationPlanStatus.DRAFT||s==ValidationPlanStatus.REJECTED;}private static ValidationPlanStatus status(ValidationPlanResponse x){return ValidationPlanStatus.valueOf(x.status());}private static LocalDateTime time(Map<String,Object>x,String k){var v=(Timestamp)x.get(k);return v==null?null:v.toLocalDateTime();}private static long actor(){return SecurityContext.getUserId().orElse(0L);}private static BusinessException error(QmsEngineeringErrorCode c){return new BusinessException(c);}
}
