create table mdm_validation_rule (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null, model_id bigint not null references mdm_model(id),
 code varchar(64) not null, name varchar(128) not null, trigger_point varchar(32) not null,
 rule_type varchar(32) not null, field_code varchar(64), severity varchar(16) not null default 'ERROR',
 message varchar(500) not null, condition_json jsonb not null default '{}'::jsonb,
 assertion_json jsonb not null, enabled boolean not null default true, sort_no int not null default 0,
 created_by bigint, created_at timestamptz not null default now(), updated_by bigint,
 updated_at timestamptz not null default now(), deleted boolean not null default false,
 version int not null default 0, ext_json jsonb,
 constraint uk_mdm_validation_rule_code unique(tenant_id,model_id,code)
);
create index idx_mdm_validation_rule_execution on mdm_validation_rule(tenant_id,model_id,trigger_point,enabled) where deleted=false;

insert into mdm_model(tenant_id,domain_id,code,name,record_type,version_enabled,effective_date_enabled,organization_scope_enabled,approval_required,status,current_model_version,ui_schema,created_by,updated_by)
select t.id,d.id,'bomItem','BOM行主数据','MASTER',true,true,false,false,'PUBLISHED',1,
 '{"form":{"sections":[{"id":"basic","titleKey":"mdm.sections.basic","columns":2,"fields":["parentMaterialCode","componentMaterialCode","quantity","unit","remark"]}]},"grid":{"columns":["businessCode","name","parentMaterialCode","componentMaterialCode","quantity","unit","lifecycleStatus"],"frozenColumns":["businessCode","name"]}}'::jsonb,0,0
from sys_tenant t join mdm_data_domain d on d.tenant_id=t.id and d.code='manufacturing'
where t.deleted=false on conflict(tenant_id,code) do nothing;

insert into mdm_model_field(tenant_id,model_id,code,name,data_type,required,searchable,sortable,list_visible,max_length,enum_options,help_text,sort_no,created_by,updated_by)
select m.tenant_id,m.id,f.code,f.name,f.type,f.required,true,true,true,f.max_length,null,f.help,f.sort_no,0,0
from mdm_model m cross join (values
 ('parentMaterialCode','父项物料编码','REFERENCE',true,128,'必须引用已生效物料',10),
 ('componentMaterialCode','组件物料编码','REFERENCE',true,128,'必须引用已生效物料',20),
 ('quantity','用量','DECIMAL',true,null,'大于 0',30),
 ('unit','单位','STRING',true,32,null,40),
 ('remark','备注','TEXT',false,500,null,50)
) as f(code,name,type,required,max_length,help,sort_no)
where m.code='bomItem' and m.deleted=false on conflict(tenant_id,model_id,code) do nothing;

insert into mdm_validation_rule(tenant_id,model_id,code,name,trigger_point,rule_type,field_code,severity,message,condition_json,assertion_json,sort_no,created_by,updated_by)
select m.tenant_id,m.id,r.code,r.name,'SAVE',r.rule_type,r.field_code,'ERROR',r.message,'{}'::jsonb,r.assertion::jsonb,r.sort_no,0,0
from mdm_model m cross join (values
 ('parent-material-active','父项物料存在且已生效','REFERENCE_EXISTS','parentMaterialCode','引用的父项物料不存在或未生效','{"targetModel":"material","conditions":[{"targetField":"businessCode","sourceField":"parentMaterialCode"},{"targetField":"lifecycleStatus","value":"ACTIVE"}]}',10),
 ('component-material-active','组件物料存在且已生效','REFERENCE_EXISTS','componentMaterialCode','引用的组件物料不存在或未生效','{"targetModel":"material","conditions":[{"targetField":"businessCode","sourceField":"componentMaterialCode"},{"targetField":"lifecycleStatus","value":"ACTIVE"}]}',20),
 ('quantity-positive','用量必须大于 0','EXPRESSION','quantity','用量必须大于 0','{">":[{"var":"quantity"},0]}',30)
) as r(code,name,rule_type,field_code,message,assertion,sort_no)
where m.code='bomItem' and m.deleted=false on conflict(tenant_id,model_id,code) do nothing;
