create table mdm_record_action (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null,
 record_id uuid not null references mdm_master_record(id),
 action varchar(32) not null,
 from_status varchar(32) not null,
 to_status varchar(32) not null,
 comment varchar(500),
 created_by bigint,
 created_at timestamptz not null default now(),
 updated_by bigint,
 updated_at timestamptz not null default now(),
 deleted boolean not null default false,
 version int not null default 0,
 ext_json jsonb
);

create index idx_mdm_record_action_tenant_record_created
 on mdm_record_action(tenant_id,record_id,created_at desc) where deleted=false;

insert into sys_permission(tenant_id,permission_code,permission_name,resource_type,module_code,action_code,created_by,updated_by)
select t.id,p.code,p.name,'API','mdm',p.action,0,0
from sys_tenant t cross join (values
 ('mdm:record:submit','Submit MDM records','submit'),
 ('mdm:record:approve','Approve or reject MDM records','approve'),
 ('mdm:record:disable','Deactivate MDM records','disable')
) p(code,name,action)
where t.deleted=false on conflict(tenant_id,permission_code) do nothing;

insert into sys_role_permission(tenant_id,role_id,permission_id,created_by,updated_by,deleted,version)
select r.tenant_id,r.id,p.id,0,0,false,0
from sys_role r join sys_permission p on p.tenant_id=r.tenant_id
where r.role_code='platform_admin' and r.deleted=false and p.deleted=false
 and p.permission_code in('mdm:record:submit','mdm:record:approve','mdm:record:disable')
on conflict(tenant_id,role_id,permission_id) do nothing;
