create table mdm_model_version (
 id bigint generated by default as identity primary key,
 tenant_id bigint not null,
 model_id bigint not null references mdm_model(id),
 version_no int not null,
 status varchar(32) not null,
 schema_snapshot jsonb not null,
 ui_schema_snapshot jsonb not null,
 published_by bigint,
 published_at timestamptz not null default now(),
 created_by bigint, created_at timestamptz not null default now(),
 updated_by bigint, updated_at timestamptz not null default now(),
 deleted boolean not null default false, version int not null default 0, ext_json jsonb,
 constraint uk_mdm_model_version unique(tenant_id,model_id,version_no)
);

insert into mdm_model_version(tenant_id,model_id,version_no,status,schema_snapshot,ui_schema_snapshot,published_by,created_by,updated_by)
select m.tenant_id,m.id,m.current_model_version,'PUBLISHED',coalesce((select jsonb_agg(to_jsonb(f) - 'tenant_id' - 'model_id' order by f.sort_no,f.id) from mdm_model_field f where f.model_id=m.id and f.deleted=false),'[]'::jsonb),m.ui_schema,0,0,0
from mdm_model m where m.status='PUBLISHED' and m.deleted=false on conflict(tenant_id,model_id,version_no) do nothing;

insert into sys_permission(tenant_id,permission_code,permission_name,resource_type,module_code,action_code,created_by,updated_by)
select t.id,p.code,p.name,'API','mdm',p.action,0,0 from sys_tenant t cross join (values
 ('mdm:model:create','Create MDM models','create'),('mdm:model:update','Update MDM model drafts','update'),('mdm:model:publish','Publish MDM models','publish')
) p(code,name,action) where t.deleted=false on conflict(tenant_id,permission_code) do nothing;
insert into sys_role_permission(tenant_id,role_id,permission_id,created_by,updated_by,deleted,version)
select r.tenant_id,r.id,p.id,0,0,false,0 from sys_role r join sys_permission p on p.tenant_id=r.tenant_id and p.permission_code in('mdm:model:create','mdm:model:update','mdm:model:publish') where r.role_code='platform_admin' and r.deleted=false and p.deleted=false on conflict(tenant_id,role_id,permission_id) do nothing;
