create table mdm_data_domain (
 id bigint generated by default as identity primary key, tenant_id bigint not null, code varchar(64) not null, name varchar(128) not null,
 description varchar(500), owner_role_id bigint, status varchar(32) not null, sort_no int not null default 0,
 created_by bigint, created_at timestamptz not null default now(), updated_by bigint, updated_at timestamptz not null default now(), deleted boolean not null default false, version int not null default 0, ext_json jsonb,
 constraint uk_mdm_domain_tenant_code unique(tenant_id,code)
);
create table mdm_model (
 id bigint generated by default as identity primary key, tenant_id bigint not null, domain_id bigint not null references mdm_data_domain(id), code varchar(64) not null, name varchar(128) not null,
 record_type varchar(32) not null, version_enabled boolean not null default true, effective_date_enabled boolean not null default false, organization_scope_enabled boolean not null default false,
 approval_required boolean not null default false, status varchar(32) not null, current_model_version int not null default 1, ui_schema jsonb not null default '{}'::jsonb,
 created_by bigint, created_at timestamptz not null default now(), updated_by bigint, updated_at timestamptz not null default now(), deleted boolean not null default false, version int not null default 0, ext_json jsonb,
 constraint uk_mdm_model_tenant_code unique(tenant_id,code)
);
create table mdm_model_field (
 id bigint generated by default as identity primary key, tenant_id bigint not null, model_id bigint not null references mdm_model(id), code varchar(64) not null, name varchar(128) not null, data_type varchar(32) not null,
 required boolean not null default false, unique_value boolean not null default false, readonly boolean not null default false, searchable boolean not null default false, sortable boolean not null default false, list_visible boolean not null default true,
 max_length int, enum_options jsonb, help_text varchar(500), deprecated boolean not null default false, sort_no int not null default 0,
 created_by bigint, created_at timestamptz not null default now(), updated_by bigint, updated_at timestamptz not null default now(), deleted boolean not null default false, version int not null default 0, ext_json jsonb,
 constraint uk_mdm_field_model_code unique(tenant_id,model_id,code)
);
create table mdm_master_record (
 id uuid primary key, tenant_id bigint not null, model_id bigint not null references mdm_model(id), business_code varchar(128) not null, name varchar(256) not null, lifecycle_status varchar(32) not null,
 current_version_no int not null, model_version_no int not null, scope_type varchar(32) not null, scope_ids jsonb not null default '[]'::jsonb, effective_from date, effective_to date, attributes jsonb not null default '{}'::jsonb,
 created_by bigint, created_at timestamptz not null default now(), updated_by bigint, updated_at timestamptz not null default now(), deleted boolean not null default false, version int not null default 0, ext_json jsonb,
 constraint uk_mdm_record_business_code unique(tenant_id,model_id,business_code), constraint ck_mdm_record_effective_range check(effective_to is null or effective_from is null or effective_to>=effective_from)
);
create table mdm_master_record_version (
 id bigint generated by default as identity primary key, tenant_id bigint not null, record_id uuid not null references mdm_master_record(id), version_no int not null, snapshot jsonb not null, change_type varchar(32) not null, change_reason varchar(500), effective_from date, effective_to date,
 created_by bigint, created_at timestamptz not null default now(), updated_by bigint, updated_at timestamptz not null default now(), deleted boolean not null default false, version int not null default 0, ext_json jsonb,
 constraint uk_mdm_record_version unique(tenant_id,record_id,version_no)
);
create index idx_mdm_model_tenant_status on mdm_model(tenant_id,status) where deleted=false;
create index idx_mdm_record_tenant_model_status on mdm_master_record(tenant_id,model_id,lifecycle_status) where deleted=false;
create index idx_mdm_record_attributes_gin on mdm_master_record using gin(attributes);

insert into mdm_data_domain(tenant_id,code,name,description,status,sort_no,created_by,updated_by)
select id,'manufacturing','制造主数据','物料、BOM 与价格等制造公共主数据','ENABLED',10,0,0 from sys_tenant where deleted=false on conflict(tenant_id,code) do nothing;
insert into mdm_model(tenant_id,domain_id,code,name,record_type,version_enabled,effective_date_enabled,organization_scope_enabled,approval_required,status,current_model_version,ui_schema,created_by,updated_by)
select t.id,d.id,'material','物料主数据','MASTER',true,true,true,true,'PUBLISHED',1,
 '{"form":{"sections":[{"id":"basic","titleKey":"mdm.sections.basic","columns":2,"fields":["specification","materialType","category","baseUnit","manufacturer","manufacturerPartNo","safetyPart","remark"]}]},"grid":{"columns":["businessCode","name","specification","materialType","baseUnit","lifecycleStatus"],"frozenColumns":["businessCode","name"]}}'::jsonb,0,0
from sys_tenant t join mdm_data_domain d on d.tenant_id=t.id and d.code='manufacturing' where t.deleted=false on conflict(tenant_id,code) do nothing;
insert into mdm_model_field(tenant_id,model_id,code,name,data_type,required,searchable,sortable,list_visible,max_length,enum_options,help_text,sort_no,created_by,updated_by)
select m.tenant_id,m.id,f.code,f.name,f.type,f.required,f.searchable,f.sortable,f.visible,f.max_length,f.options::jsonb,f.help,f.sort_no,0,0
from mdm_model m cross join (values
 ('specification','规格型号','STRING',false,true,true,true,256,null,'产品规格或型号',10),
 ('materialType','物料类型','ENUM',true,true,true,true,32,'["RAW","SEMI_FINISHED","FINISHED","AUXILIARY"]','选择物料业务类型',20),
 ('category','物料分类','STRING',false,true,true,true,128,null,null,30),('baseUnit','基本计量单位','STRING',true,true,true,true,32,null,null,40),
 ('manufacturer','制造商','STRING',false,true,true,true,128,null,null,50),('manufacturerPartNo','制造商料号','STRING',false,true,true,true,128,null,null,60),
 ('safetyPart','是否安全件','BOOLEAN',false,true,true,true,null,null,null,70),('remark','备注','TEXT',false,false,false,false,1000,null,null,80)
) as f(code,name,type,required,searchable,sortable,visible,max_length,options,help,sort_no)
where m.code='material' and m.deleted=false on conflict(tenant_id,model_id,code) do nothing;

insert into sys_permission(tenant_id,permission_code,permission_name,resource_type,module_code,action_code,created_by,updated_by)
select t.id,p.code,p.name,'API','mdm',p.action,0,0 from sys_tenant t cross join (values ('mdm:model:view','View MDM models','view'),('mdm:record:view','View MDM records','view'),('mdm:record:create','Create MDM records','create'),('mdm:record:update','Update MDM records','update')) p(code,name,action)
where t.deleted=false on conflict(tenant_id,permission_code) do nothing;
insert into sys_role_permission(tenant_id,role_id,permission_id,created_by,updated_by,deleted,version)
select r.tenant_id,r.id,p.id,0,0,false,0 from sys_role r join sys_permission p on p.tenant_id=r.tenant_id and p.permission_code like 'mdm:%' where r.role_code='platform_admin' and r.deleted=false and p.deleted=false on conflict(tenant_id,role_id,permission_id) do nothing;
insert into sys_menu(tenant_id,parent_id,menu_code,menu_type,title_key,route_path,component_key,icon,sort_no,visible,enabled,created_by,updated_by)
select id,null,'mdm','GROUP','menu.mdm',null,null,'DatabaseOutlined',300,true,true,0,0 from sys_tenant where deleted=false on conflict(tenant_id,menu_code) do nothing;
insert into sys_menu(tenant_id,parent_id,menu_code,menu_type,title_key,route_path,component_key,icon,sort_no,visible,enabled,created_by,updated_by)
select t.id,g.id,x.code,'MENU',x.title,x.route,x.component,'DatabaseOutlined',x.sort_no,true,true,0,0 from sys_tenant t join sys_menu g on g.tenant_id=t.id and g.menu_code='mdm' cross join (values ('mdm.models','menu.mdmModels','/mdm/models','mdm/MdmModelCenterPage',310),('mdm.material','menu.mdmMaterial','/mdm/models/material/records','mdm/MdmRecordWorkspacePage',320)) x(code,title,route,component,sort_no)
where t.deleted=false on conflict(tenant_id,menu_code) do nothing;
insert into sys_menu_permission(tenant_id,menu_id,permission_id,created_by,updated_by,deleted,version)
select m.tenant_id,m.id,p.id,0,0,false,0 from sys_menu m join sys_permission p on p.tenant_id=m.tenant_id and p.permission_code=case when m.menu_code='mdm.models' then 'mdm:model:view' else 'mdm:record:view' end where m.menu_code in('mdm.models','mdm.material') and m.deleted=false on conflict(tenant_id,menu_id,permission_id) do nothing;
insert into sys_role_menu(tenant_id,role_id,menu_id,created_by,updated_by,deleted,version)
select r.tenant_id,r.id,m.id,0,0,false,0 from sys_role r join sys_menu m on m.tenant_id=r.tenant_id and m.menu_code in('mdm','mdm.models','mdm.material') where r.role_code='platform_admin' and r.deleted=false and m.deleted=false on conflict(tenant_id,role_id,menu_id) do nothing;
