import { apiClient } from '../../api/client';
import type { CreateMdmModel, MdmApprovalTask, MdmApprovalTaskScope, MdmBatchDeleteItem, MdmBatchUpdateItem, MdmBatchValidation, MdmImportPreview, MdmImportTask, MdmModel, MdmModelApprovalTask, MdmModelDictionaryPreview, MdmModelValidation, MdmPage, MdmRecord, MdmRecordAction, MdmRecordActionType, MdmRecordVersion, MdmValidationOutcome, MdmValidationRule, SaveMdmModelDraft, SaveMdmRecord } from './types';
export const mdmApi = {
  models: () => apiClient.get<MdmModel[]>('/api/mdm/models'),
  approvalTasks: (scope:MdmApprovalTaskScope) => apiClient.get<MdmApprovalTask[]>('/api/mdm/models/approval-tasks',{query:{scope}}),
  modelApprovalTasks: (scope:MdmApprovalTaskScope) => apiClient.get<MdmModelApprovalTask[]>('/api/mdm/models/model-approval-tasks',{query:{scope}}),
  schema: (code:string) => apiClient.get<MdmModel>(`/api/mdm/models/${code}/schema`),
  createModel: (request:CreateMdmModel) => apiClient.post<MdmModel>('/api/mdm/models',request),
  modelDictionaryTemplate: () => apiClient.getBlob('/api/mdm/models/dictionary-import-template'),
  previewModelDictionary: (file:File) => { const body=new FormData(); body.append('file',file); return apiClient.post<MdmModelDictionaryPreview>('/api/mdm/models/dictionary-imports/preview',body); },
  saveDraft: (code:string,request:SaveMdmModelDraft) => apiClient.put<MdmModel>(`/api/mdm/models/${code}/draft`,request),
  validateModel: (code:string) => apiClient.post<MdmModelValidation>(`/api/mdm/models/${code}/validate`,{}),
  publishModel: (code:string) => apiClient.post<MdmModel>(`/api/mdm/models/${code}/publish`,{}),
  modelPublishAction: (code:string,action:'APPROVE'|'REJECT',comment:string) => apiClient.post<MdmModel>(`/api/mdm/models/${code}/publish/${action.toLowerCase()}`,{comment}),
  validationRules:(code:string)=>apiClient.get<MdmValidationRule[]>(`/api/mdm/models/${code}/validation-rules`),
  saveValidationRules:(code:string,rules:MdmValidationRule[])=>apiClient.put<MdmValidationRule[]>(`/api/mdm/models/${code}/validation-rules`,{rules}),
  validateField:(code:string,fieldCode:string,record:SaveMdmRecord)=>apiClient.post<MdmValidationOutcome>(`/api/mdm/models/${code}/records/validate-field`,{fieldCode,record}),
  records: (code:string, params:{keyword?:string;pageNo:number;pageSize:number}) => apiClient.get<MdmPage<MdmRecord>>(`/api/mdm/models/${code}/records`,{query:params}),
  recordVersions: (code:string,id:string) => apiClient.get<MdmRecordVersion[]>(`/api/mdm/models/${code}/records/${id}/versions`),
  recordActions: (code:string,id:string) => apiClient.get<MdmRecordAction[]>(`/api/mdm/models/${code}/records/${id}/actions`),
  recordAction: (code:string,id:string,action:MdmRecordActionType,comment:string) => apiClient.post<MdmRecord>(`/api/mdm/models/${code}/records/${id}/${action === 'DEACTIVATE' ? 'deactivate' : action.toLowerCase()}`,{comment}),
  create: (code:string, request:SaveMdmRecord) => apiClient.post<MdmRecord>(`/api/mdm/models/${code}/records`,request),
  validateBatch: (code:string,records:SaveMdmRecord[]) => apiClient.post<MdmBatchValidation>(`/api/mdm/models/${code}/records/batch-validate`,{records}),
  createBatch: (code:string,records:SaveMdmRecord[]) => apiClient.post<MdmRecord[]>(`/api/mdm/models/${code}/records/batch`,{records}),
  importTemplate: (code:string) => apiClient.getBlob(`/api/mdm/models/${code}/import-template`),
  previewImport: (code:string,file:File) => { const body=new FormData(); body.append('file',file); return apiClient.post<MdmImportPreview>(`/api/mdm/models/${code}/imports`,body); },
  queueImport: (code:string,file:File) => { const body=new FormData(); body.append('file',file); return apiClient.post<MdmImportTask>(`/api/mdm/models/${code}/imports/async`,body); },
  importTasks: (code:string) => apiClient.get<MdmImportTask[]>(`/api/mdm/models/${code}/imports`),
  importErrors: (code:string,taskId:string) => apiClient.get<MdmBatchValidation>(`/api/mdm/models/${code}/imports/${taskId}/errors`),
  commitImport: (code:string,taskId:string) => apiClient.post<MdmImportTask>(`/api/mdm/models/${code}/imports/${taskId}/commit`,{}),
  importSource: (code:string,taskId:string) => apiClient.getBlob(`/api/mdm/models/${code}/imports/${taskId}/source`),
  importResult: (code:string,taskId:string) => apiClient.getBlob(`/api/mdm/models/${code}/imports/${taskId}/result`),
  update: (code:string,id:string,request:SaveMdmRecord) => apiClient.put<MdmRecord>(`/api/mdm/models/${code}/records/${id}`,request),
  updateBatch: (code:string,items:MdmBatchUpdateItem[]) => apiClient.put<MdmRecord[]>(`/api/mdm/models/${code}/records/batch`,{items}),
  deleteBatch: (code:string,items:MdmBatchDeleteItem[]) => apiClient.request<void>(`/api/mdm/models/${code}/records/batch`,{method:'DELETE',body:{items}})
};
