create table qms_quality_characteristic (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    part_id bigint not null,
    drawing_revision_id bigint not null,
    source_entity_id varchar(128),
    evidence_id bigint not null,
    characteristic_code varchar(64) not null,
    characteristic_type varchar(32) not null,
    name varchar(255) not null,
    nominal_value numeric(18,6),
    upper_tolerance numeric(18,6),
    lower_tolerance numeric(18,6),
    upper_limit numeric(18,6),
    lower_limit numeric(18,6),
    unit varchar(32),
    special_characteristic_code varchar(64),
    confidence numeric(5,4) not null,
    status varchar(32) not null default 'DRAFT',
    review_status varchar(32) not null default 'PENDING',
    reviewed_by bigint,
    reviewed_at timestamp,
    review_comment varchar(1000),
    created_by bigint, created_at timestamp not null default current_timestamp,
    updated_by bigint, updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false, version int not null default 0, ext_json jsonb,
    constraint uk_qms_characteristic_tenant_id unique (tenant_id, id),
    constraint uk_qms_characteristic_revision_code unique (tenant_id, drawing_revision_id, characteristic_code),
    constraint uk_qms_characteristic_revision_evidence unique (tenant_id, drawing_revision_id, evidence_id),
    constraint fk_qms_characteristic_part foreign key (tenant_id, part_id) references qms_part (tenant_id, id),
    constraint fk_qms_characteristic_revision foreign key (tenant_id, drawing_revision_id) references qms_drawing_revision (tenant_id, id),
    constraint fk_qms_characteristic_evidence foreign key (tenant_id, evidence_id) references qms_source_evidence (tenant_id, id),
    constraint ck_qms_characteristic_type check (characteristic_type in ('DIMENSION','APPEARANCE','MATERIAL','PERFORMANCE','REGULATORY','LABEL','PACKAGING','TECHNICAL_REQUIREMENT','OTHER')),
    constraint ck_qms_characteristic_review check (review_status in ('PENDING','CONFIRMED','REJECTED')),
    constraint ck_qms_characteristic_confidence check (confidence >= 0 and confidence <= 1)
);

create index idx_qms_characteristic_revision on qms_quality_characteristic
    (tenant_id, org_id, drawing_revision_id, review_status) where deleted=false;

insert into sys_permission
    (tenant_id, permission_code, permission_name, resource_type, module_code, action_code,
     created_by, updated_by, deleted, version)
select t.id, 'qms:quality-characteristic:review', 'Review quality characteristics', 'API', 'qms', 'review',
       1, 1, false, 0
from sys_tenant t
where t.deleted=false and not exists (select 1 from sys_permission where tenant_id=t.id
    and permission_code='qms:quality-characteristic:review' and deleted=false);

insert into sys_role_permission
    (tenant_id, role_id, permission_id, created_by, updated_by, deleted, version)
select r.tenant_id, r.id, p.id, 1, 1, false, 0
from sys_role r join sys_permission p on p.tenant_id=r.tenant_id
where r.role_code='platform_admin' and r.deleted=false and p.deleted=false
  and p.permission_code='qms:quality-characteristic:review'
  and not exists (select 1 from sys_role_permission rp where rp.tenant_id=r.tenant_id
    and rp.role_id=r.id and rp.permission_id=p.id and rp.deleted=false);
