create table qms_drawing_parse_job (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    revision_id bigint not null,
    file_id bigint not null,
    attempt_no int not null,
    status varchar(32) not null,
    parser_type varchar(32) not null,
    error_code varchar(64),
    error_message varchar(1000),
    started_at timestamp,
    completed_at timestamp,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_qms_parse_job_tenant_id unique (tenant_id, id),
    constraint uk_qms_parse_job_revision_attempt unique (tenant_id, revision_id, attempt_no),
    constraint fk_qms_parse_job_revision foreign key (tenant_id, revision_id)
        references qms_drawing_revision (tenant_id, id),
    constraint fk_qms_parse_job_file foreign key (tenant_id, file_id)
        references qms_file_object (tenant_id, id),
    constraint ck_qms_parse_job_attempt check (attempt_no > 0),
    constraint ck_qms_parse_job_status check (status in ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED'))
);

create index idx_qms_parse_job_claim on qms_drawing_parse_job
    (tenant_id, status, created_at) where deleted=false;
create unique index uk_qms_parse_job_active_revision on qms_drawing_parse_job
    (tenant_id, revision_id) where deleted=false and status in ('QUEUED','RUNNING');

insert into sys_permission
    (tenant_id, permission_code, permission_name, resource_type, module_code, action_code,
     created_by, updated_by, deleted, version)
select t.id, 'qms:drawing-revision:retry-parse', 'Retry drawing parse', 'API', 'qms', 'retry-parse',
       1, 1, false, 0
from sys_tenant t
where t.deleted=false and not exists (select 1 from sys_permission where tenant_id=t.id
    and permission_code='qms:drawing-revision:retry-parse' and deleted=false);

insert into sys_role_permission
    (tenant_id, role_id, permission_id, created_by, updated_by, deleted, version)
select r.tenant_id, r.id, p.id, 1, 1, false, 0
from sys_role r join sys_permission p on p.tenant_id=r.tenant_id
where r.role_code='platform_admin' and r.deleted=false and p.deleted=false
  and p.permission_code='qms:drawing-revision:retry-parse'
  and not exists (select 1 from sys_role_permission rp where rp.tenant_id=r.tenant_id
    and rp.role_id=r.id and rp.permission_id=p.id and rp.deleted=false);
