create table qms_drawing_legend_rule (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    rule_code varchar(32) not null,
    marker varchar(32) not null,
    description varchar(128) not null,
    target_field varchar(32) not null,
    target_value varchar(32),
    match_mode varchar(16) not null default 'CONTAINS',
    priority int not null default 100,
    enabled boolean not null default true,
    created_by bigint, created_at timestamp not null default current_timestamp,
    updated_by bigint, updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false, version int not null default 0,
    constraint uk_qms_legend_tenant_id unique (tenant_id,id),
    constraint uk_qms_legend_code unique (tenant_id,rule_code),
    constraint uk_qms_legend_marker unique (tenant_id,marker),
    constraint fk_qms_legend_tenant foreign key (tenant_id) references sys_tenant(id),
    constraint ck_qms_legend_target check (target_field in
      ('INSPECTION_DIMENSION','LOCATION_DIMENSION','FIT_DIMENSION','REFERENCE_DIMENSION','SPECIAL_CODE','REGULATORY_FLAG')),
    constraint ck_qms_legend_mode check (match_mode in ('CONTAINS','WRAPS_VALUE'))
);

insert into qms_drawing_legend_rule
 (tenant_id,rule_code,marker,description,target_field,target_value,match_mode,priority,created_by,updated_by)
select t.id,v.rule_code,v.marker,v.description,v.target_field,v.target_value,v.match_mode,v.priority,0,0
from sys_tenant t cross join (values
 ('INSPECTION','◆','检验尺寸','INSPECTION_DIMENSION',null,'CONTAINS',10),
 ('LOCATION','▲','定位尺寸','LOCATION_DIMENSION',null,'CONTAINS',20),
 ('FIT','★','配合尺寸','FIT_DIMENSION',null,'CONTAINS',30),
 ('REFERENCE','()','括号包裹的参考尺寸','REFERENCE_DIMENSION',null,'WRAPS_VALUE',40),
 ('IMPORTANT_B','[B]','重要特性','SPECIAL_CODE','B','CONTAINS',50),
 ('CRITICAL_A','[A]','关键特性','SPECIAL_CODE','A','CONTAINS',60),
 ('REGULATORY_R','[R]','法规特性','REGULATORY_FLAG','R','CONTAINS',70)
) v(rule_code,marker,description,target_field,target_value,match_mode,priority)
where t.deleted=false on conflict do nothing;

update qms_quality_characteristic set
 inspection_dimension=position('◆' in name)>0,
 location_dimension=position('▲' in name)>0,
 fit_dimension=position('★' in name)>0,
 reference_dimension=(ltrim(name) like '(%' or
   (left(ltrim(name),1)='[' and substring(ltrim(name),3,1)=']' and ltrim(substring(ltrim(name),4)) like '(%')),
 regulatory_flag=position('[R]' in name)>0,
 special_characteristic_code=case when position('[A]' in name)>0 then 'A' when position('[B]' in name)>0 then 'B' when position('[R]' in name)>0 then 'R' else null end
where review_status='PENDING' and evidence_id is not null and deleted=false;
update qms_quality_characteristic set inspection_dimension=false
where review_status='PENDING' and reference_dimension=true and deleted=false;

insert into sys_permission
 (tenant_id,permission_code,permission_name,resource_type,module_code,action_code,created_by,updated_by,deleted,version)
select t.id,'qms:drawing-legend:manage','Manage drawing legend rules','API','qms','manage',0,0,false,0
from sys_tenant t where t.deleted=false and not exists (select 1 from sys_permission p where p.tenant_id=t.id and p.permission_code='qms:drawing-legend:manage' and p.deleted=false);

insert into sys_role_permission (tenant_id,role_id,permission_id,created_by,updated_by,deleted,version)
select r.tenant_id,r.id,p.id,0,0,false,0 from sys_role r join sys_permission p on p.tenant_id=r.tenant_id
where r.role_code='platform_admin' and r.deleted=false and p.permission_code='qms:drawing-legend:manage' and p.deleted=false
on conflict (tenant_id,role_id,permission_id) do nothing;

insert into sys_menu (tenant_id,parent_id,menu_code,menu_type,title_key,route_path,component_key,icon,sort_no,visible,enabled,created_by,updated_by)
select t.id,p.id,'qms.engineering.legend','MENU','menu.qmsDrawingLegend','/qms/engineering/drawing-legend',
 'qms/engineering/QmsDrawingLegendConfigPage','SettingOutlined',420,true,true,0,0
from sys_tenant t join sys_menu p on p.tenant_id=t.id and p.menu_code='qms' and p.deleted=false
on conflict (tenant_id,menu_code) do nothing;

insert into sys_menu_permission (tenant_id,menu_id,permission_id,created_by,updated_by)
select m.tenant_id,m.id,p.id,0,0 from sys_menu m join sys_permission p on p.tenant_id=m.tenant_id
where m.menu_code='qms.engineering.legend' and m.deleted=false and p.permission_code='qms:drawing-legend:manage' and p.deleted=false
on conflict (tenant_id,menu_id,permission_id) do nothing;

insert into sys_role_menu (tenant_id,role_id,menu_id,created_by,updated_by)
select r.tenant_id,r.id,m.id,0,0 from sys_role r join sys_menu m on m.tenant_id=r.tenant_id
where r.role_code='platform_admin' and r.deleted=false and m.menu_code='qms.engineering.legend' and m.deleted=false
on conflict (tenant_id,role_id,menu_id) do nothing;
