create table qms_drawing_revision_file (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    revision_id bigint not null,
    file_id bigint not null,
    file_role varchar(32) not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    constraint uk_qms_revision_file_tenant_id unique (tenant_id, id),
    constraint fk_qms_revision_file_revision foreign key (tenant_id, revision_id)
        references qms_drawing_revision (tenant_id, id),
    constraint fk_qms_revision_file_object foreign key (tenant_id, file_id)
        references qms_file_object (tenant_id, id),
    constraint ck_qms_revision_file_role check (file_role in ('DWG_SOURCE', 'PDF_REFERENCE'))
);

create unique index uk_qms_revision_file_active_role
    on qms_drawing_revision_file (tenant_id, revision_id, file_role) where deleted = false;

insert into qms_drawing_revision_file
    (tenant_id, org_id, revision_id, file_id, file_role, created_by, updated_by)
select tenant_id, org_id, id, file_id,
       case when file_type = 'DWG' then 'DWG_SOURCE' else 'PDF_REFERENCE' end,
       coalesce(created_by, 0), coalesce(updated_by, 0)
from qms_drawing_revision
where file_id is not null and deleted = false
on conflict do nothing;
