create table qms_file_object (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    original_name varchar(255) not null,
    media_type varchar(128) not null,
    file_extension varchar(16) not null,
    size_bytes bigint not null,
    checksum_sha256 varchar(64) not null,
    storage_bucket varchar(128) not null,
    storage_object_key varchar(512) not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_qms_file_object_tenant_id unique (tenant_id, id),
    constraint uk_qms_file_object_storage_key unique (storage_bucket, storage_object_key),
    constraint ck_qms_file_object_size check (size_bytes > 0)
);

create index idx_qms_file_object_tenant_org_checksum
    on qms_file_object (tenant_id, org_id, checksum_sha256) where deleted = false;

alter table qms_drawing_revision
    add constraint fk_qms_revision_file foreign key (tenant_id, file_id)
        references qms_file_object (tenant_id, id);

insert into sys_permission
    (tenant_id, permission_code, permission_name, resource_type, module_code, action_code,
     created_by, updated_by, deleted, version)
select 1, 'qms:drawing-revision:upload', 'Upload drawing revision file', 'API', 'qms', 'upload',
       1, 1, false, 0
where not exists (
    select 1 from sys_permission where tenant_id = 1
      and permission_code = 'qms:drawing-revision:upload' and deleted = false
);

insert into sys_role_permission
    (tenant_id, role_id, permission_id, created_by, updated_by, deleted, version)
select r.tenant_id, r.id, p.id, 1, 1, false, 0
from sys_role r
join sys_permission p on p.tenant_id = r.tenant_id
where r.tenant_id = 1 and r.role_code = 'ADMIN'
  and p.permission_code = 'qms:drawing-revision:upload'
  and not exists (
      select 1 from sys_role_permission rp where rp.tenant_id = r.tenant_id
        and rp.role_id = r.id and rp.permission_id = p.id and rp.deleted = false
  );

