create table qms_part (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    part_no varchar(128) not null,
    material_no varchar(128),
    part_name varchar(256) not null,
    customer_id bigint,
    vehicle_model varchar(128),
    supplier_id bigint,
    importance_level varchar(32),
    status varchar(32) not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_qms_part_tenant_id unique (tenant_id, id)
);

create unique index uk_qms_part_org_no_active
    on qms_part (tenant_id, org_id, part_no) where deleted = false;
create index idx_qms_part_tenant_org_status
    on qms_part (tenant_id, org_id, status);
create index idx_qms_part_tenant_created
    on qms_part (tenant_id, created_at desc);

create table qms_drawing (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    part_id bigint not null,
    drawing_no varchar(128) not null,
    drawing_name varchar(256) not null,
    drawing_type varchar(32) not null,
    source_system varchar(64) not null,
    status varchar(32) not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_qms_drawing_tenant_id unique (tenant_id, id),
    constraint fk_qms_drawing_part foreign key (tenant_id, part_id)
        references qms_part (tenant_id, id)
);

create unique index uk_qms_drawing_part_no_active
    on qms_drawing (tenant_id, part_id, drawing_no) where deleted = false;
create index idx_qms_drawing_tenant_org_status
    on qms_drawing (tenant_id, org_id, status);
create index idx_qms_drawing_tenant_part
    on qms_drawing (tenant_id, part_id);

create table qms_drawing_revision (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    drawing_id bigint not null,
    revision_code varchar(64) not null,
    revision_seq int not null,
    file_id bigint,
    file_type varchar(16),
    effective_date date,
    release_date date,
    supersedes_revision_id bigint,
    parse_status varchar(32) not null,
    review_status varchar(32) not null,
    status varchar(32) not null,
    checksum varchar(128),
    released_by bigint,
    released_at timestamp,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_qms_drawing_revision_tenant_id unique (tenant_id, id),
    constraint fk_qms_revision_drawing foreign key (tenant_id, drawing_id)
        references qms_drawing (tenant_id, id),
    constraint fk_qms_revision_supersedes foreign key (tenant_id, supersedes_revision_id)
        references qms_drawing_revision (tenant_id, id),
    constraint ck_qms_revision_seq_positive check (revision_seq > 0)
);

create unique index uk_qms_revision_code_active
    on qms_drawing_revision (tenant_id, drawing_id, revision_code) where deleted = false;
create unique index uk_qms_revision_seq_active
    on qms_drawing_revision (tenant_id, drawing_id, revision_seq) where deleted = false;
create index idx_qms_revision_tenant_org_status
    on qms_drawing_revision (tenant_id, org_id, status);
create index idx_qms_revision_tenant_drawing
    on qms_drawing_revision (tenant_id, drawing_id, revision_seq desc);

create table qms_audit_log (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    actor_id bigint,
    action varchar(128) not null,
    object_type varchar(64) not null,
    object_id bigint not null,
    before_json jsonb,
    after_json jsonb,
    source varchar(32) not null,
    trace_id varchar(64) not null,
    ip varchar(64),
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb
);

create index idx_qms_audit_tenant_object
    on qms_audit_log (tenant_id, object_type, object_id, created_at desc);
create index idx_qms_audit_tenant_actor
    on qms_audit_log (tenant_id, actor_id, created_at desc);

insert into sys_permission
    (tenant_id, permission_code, permission_name, resource_type, module_code, action_code,
     created_by, created_at, updated_by, updated_at, deleted, version)
select t.id, permission_code, permission_name, 'API', 'qms', action_code,
       0, current_timestamp, 0, current_timestamp, false, 0
from sys_tenant t
cross join (values
    ('qms:part:view', 'View QMS parts', 'view'),
    ('qms:part:create', 'Create QMS parts', 'create'),
    ('qms:drawing:view', 'View QMS drawings', 'view'),
    ('qms:drawing:create', 'Create QMS drawings', 'create'),
    ('qms:drawing-revision:view', 'View QMS drawing revisions', 'view'),
    ('qms:drawing-revision:create', 'Create QMS drawing revisions', 'create')
) as p(permission_code, permission_name, action_code)
where not exists (
    select 1 from sys_permission existing
    where existing.tenant_id = t.id
      and existing.permission_code = p.permission_code
      and existing.deleted = false
);

insert into sys_role_permission
    (tenant_id, role_id, permission_id, created_by, created_at, updated_by, updated_at,
     deleted, version)
select r.tenant_id, r.id, p.id, 0, current_timestamp, 0, current_timestamp, false, 0
from sys_role r
join sys_permission p on p.tenant_id = r.tenant_id and p.module_code = 'qms' and p.deleted = false
where r.role_code = 'platform_admin'
  and r.deleted = false
  and not exists (
      select 1 from sys_role_permission rp
      where rp.tenant_id = r.tenant_id
        and rp.role_id = r.id
        and rp.permission_id = p.id
        and rp.deleted = false
  );
