create table qms_drawing_intermediate_model (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    revision_id bigint not null,
    parse_job_id bigint not null,
    schema_version varchar(32) not null,
    document_id varchar(128) not null,
    revision_code varchar(64) not null,
    model_json jsonb not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_qms_dim_tenant_id unique (tenant_id, id),
    constraint uk_qms_dim_revision unique (tenant_id, revision_id),
    constraint fk_qms_dim_revision foreign key (tenant_id, revision_id)
        references qms_drawing_revision (tenant_id, id),
    constraint fk_qms_dim_parse_job foreign key (tenant_id, parse_job_id)
        references qms_drawing_parse_job (tenant_id, id)
);

create table qms_drawing_entity (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    revision_id bigint not null,
    parse_job_id bigint not null,
    entity_id varchar(128) not null,
    source_entity_handle varchar(128),
    entity_type varchar(32) not null,
    layer_name varchar(128),
    sheet_no varchar(32) not null,
    bbox_x numeric(18,6),
    bbox_y numeric(18,6),
    bbox_w numeric(18,6),
    bbox_h numeric(18,6),
    geometry_json jsonb,
    raw_text text,
    normalized_text text,
    style_json jsonb,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_qms_entity_tenant_id unique (tenant_id, id),
    constraint uk_qms_entity_revision_key unique (tenant_id, revision_id, entity_id),
    constraint fk_qms_entity_revision foreign key (tenant_id, revision_id)
        references qms_drawing_revision (tenant_id, id),
    constraint fk_qms_entity_parse_job foreign key (tenant_id, parse_job_id)
        references qms_drawing_parse_job (tenant_id, id)
);

create index idx_qms_entity_revision_type on qms_drawing_entity
    (tenant_id, org_id, revision_id, entity_type) where deleted=false;

create table qms_source_evidence (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    org_id bigint not null,
    source_file_id bigint not null,
    drawing_revision_id bigint not null,
    parse_job_id bigint not null,
    evidence_key varchar(128) not null,
    entity_id varchar(128),
    entity_handle varchar(128),
    sheet_no varchar(32) not null,
    page_no int,
    bbox_x numeric(18,6) not null,
    bbox_y numeric(18,6) not null,
    bbox_w numeric(18,6) not null,
    bbox_h numeric(18,6) not null,
    raw_text text,
    normalized_text text,
    extractor_type varchar(32) not null,
    extractor_version varchar(64) not null,
    model_name varchar(128),
    model_version varchar(64),
    confidence numeric(5,4) not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_qms_evidence_tenant_id unique (tenant_id, id),
    constraint uk_qms_evidence_revision_key unique (tenant_id, drawing_revision_id, evidence_key),
    constraint fk_qms_evidence_file foreign key (tenant_id, source_file_id)
        references qms_file_object (tenant_id, id),
    constraint fk_qms_evidence_revision foreign key (tenant_id, drawing_revision_id)
        references qms_drawing_revision (tenant_id, id),
    constraint fk_qms_evidence_parse_job foreign key (tenant_id, parse_job_id)
        references qms_drawing_parse_job (tenant_id, id),
    constraint ck_qms_evidence_page check (page_no is null or page_no > 0),
    constraint ck_qms_evidence_bbox check (bbox_w >= 0 and bbox_h >= 0),
    constraint ck_qms_evidence_confidence check (confidence >= 0 and confidence <= 1),
    constraint ck_qms_evidence_extractor check (extractor_type in
        ('PDF_VECTOR','OCR','DWG_ENTITY','VLM','LLM','RULE','MANUAL'))
);

create index idx_qms_evidence_revision on qms_source_evidence
    (tenant_id, org_id, drawing_revision_id, sheet_no, page_no) where deleted=false;
create index idx_qms_evidence_entity on qms_source_evidence
    (tenant_id, drawing_revision_id, entity_id) where deleted=false and entity_id is not null;
