create table qms_validation_plan (
 id bigint generated by default as identity primary key, tenant_id bigint not null, org_id bigint not null,
 plan_no varchar(64) not null, part_id bigint not null, inspection_standard_id bigint not null,
 drawing_revision_id bigint not null, document_version int not null default 1,
 status varchar(32) not null default 'AI_GENERATED', approval_status varchar(32) not null default 'NOT_SUBMITTED',
 supplier_id bigint, submitted_by bigint, submitted_at timestamp, approved_by bigint, approved_at timestamp,
 released_by bigint, released_at timestamp,
 created_by bigint, created_at timestamp not null default current_timestamp, updated_by bigint,
 updated_at timestamp not null default current_timestamp, deleted boolean not null default false,
 version int not null default 0, ext_json jsonb not null default '{}',
 unique(tenant_id,id), unique(tenant_id,inspection_standard_id,document_version),
 foreign key(tenant_id,part_id) references qms_part(tenant_id,id),
 foreign key(tenant_id,inspection_standard_id) references qms_inspection_standard(tenant_id,id),
 foreign key(tenant_id,drawing_revision_id) references qms_drawing_revision(tenant_id,id));

create table qms_validation_plan_item (
 id bigint generated by default as identity primary key, tenant_id bigint not null, org_id bigint not null,
 validation_plan_id bigint not null, sequence_no int not null, test_item varchar(255) not null,
 standard_source varchar(1000), method_acceptance_criteria varchar(1000), laboratory_id bigint,
 dv_required boolean not null default false, pv_required boolean not null default false,
 type_required boolean not null default false, batch_required boolean not null default false,
 quantity int, start_date date, end_date date, equivalent_info varchar(1000),
 source_inspection_item_id bigint not null, source_characteristic_id bigint not null, evidence_id bigint,
 review_status varchar(32) not null default 'PENDING',
 created_by bigint, created_at timestamp not null default current_timestamp, updated_by bigint,
 updated_at timestamp not null default current_timestamp, deleted boolean not null default false,
 version int not null default 0, ext_json jsonb not null default '{}',
 unique(tenant_id,id), unique(tenant_id,validation_plan_id,sequence_no),
 foreign key(tenant_id,validation_plan_id) references qms_validation_plan(tenant_id,id),
 foreign key(tenant_id,source_inspection_item_id) references qms_inspection_standard_item(tenant_id,id),
 foreign key(tenant_id,source_characteristic_id) references qms_quality_characteristic(tenant_id,id));

create index idx_qms_validation_plan_source on qms_validation_plan(tenant_id,org_id,inspection_standard_id,deleted);

insert into sys_permission(tenant_id,permission_code,permission_name,resource_type,module_code,action_code,created_by,updated_by,deleted,version)
select t.id,p.code,p.name,'API','qms',p.action,0,0,false,0 from sys_tenant t cross join(values
 ('qms:validation-plan:edit','Edit validation plan drafts','edit'),
 ('qms:validation-plan:submit','Submit validation plan','submit'),
 ('qms:validation-plan:approve','Approve validation plan','approve'),
 ('qms:validation-plan:release','Release validation plan','release'))p(code,name,action)
where not t.deleted and not exists(select 1 from sys_permission x where x.tenant_id=t.id and x.permission_code=p.code and not x.deleted);

insert into sys_role_permission(tenant_id,role_id,permission_id,created_by,updated_by,deleted,version)
select r.tenant_id,r.id,p.id,0,0,false,0 from sys_role r join sys_permission p on p.tenant_id=r.tenant_id
where r.role_code='platform_admin' and not r.deleted and p.permission_code like 'qms:validation-plan:%' and not p.deleted
on conflict(tenant_id,role_id,permission_id) do nothing;
