create table platform_approval_instance (
 id bigint generated by default as identity primary key, tenant_id bigint not null, org_id bigint not null,
 business_type varchar(64) not null, business_id bigint not null, approval_status varchar(32) not null,
 submitted_by bigint not null, submitted_at timestamp not null default current_timestamp,
 decided_by bigint, decided_at timestamp, decision_comment varchar(1000),
 created_by bigint, created_at timestamp not null default current_timestamp, updated_by bigint,
 updated_at timestamp not null default current_timestamp, deleted boolean not null default false,
 version int not null default 0, ext_json jsonb not null default '{}'
);
create index idx_platform_approval_business on platform_approval_instance(tenant_id,org_id,business_type,business_id,id desc);
create table platform_approval_action (
 id bigint generated by default as identity primary key, tenant_id bigint not null, org_id bigint not null,
 approval_instance_id bigint not null, action_code varchar(32) not null, actor_id bigint not null,
 comment varchar(1000), acted_at timestamp not null default current_timestamp,
 created_by bigint, created_at timestamp not null default current_timestamp, updated_by bigint,
 updated_at timestamp not null default current_timestamp, deleted boolean not null default false,
 version int not null default 0, ext_json jsonb not null default '{}',
 foreign key(approval_instance_id) references platform_approval_instance(id)
);
alter table qms_inspection_standard add column approval_status varchar(32) not null default 'NOT_SUBMITTED';
alter table qms_inspection_standard add column submitted_by bigint;
alter table qms_inspection_standard add column submitted_at timestamp;
alter table qms_inspection_standard add column approved_by bigint;
alter table qms_inspection_standard add column approved_at timestamp;
alter table qms_inspection_standard add column released_by bigint;
alter table qms_inspection_standard add column released_at timestamp;
alter table qms_inspection_standard add column ext_json jsonb not null default '{}';
alter table qms_inspection_standard_item add column ext_json jsonb not null default '{}';
insert into sys_permission(tenant_id,permission_code,permission_name,resource_type,module_code,action_code,created_by,updated_by,deleted,version)
select t.id,p.code,p.name,'API','qms',p.action,0,0,false,0 from sys_tenant t cross join(values
 ('qms:inspection-standard:submit','Submit inspection standard','submit'),
 ('qms:inspection-standard:approve','Approve inspection standard','approve'),
 ('qms:inspection-standard:release','Release inspection standard','release'))p(code,name,action)
where t.deleted=false and not exists(select 1 from sys_permission x where x.tenant_id=t.id and x.permission_code=p.code and not x.deleted);
insert into sys_role_permission(tenant_id,role_id,permission_id,created_by,updated_by,deleted,version)
select r.tenant_id,r.id,p.id,0,0,false,0 from sys_role r join sys_permission p on p.tenant_id=r.tenant_id
where r.role_code='platform_admin' and not r.deleted and p.permission_code in('qms:inspection-standard:submit','qms:inspection-standard:approve','qms:inspection-standard:release') and not p.deleted
on conflict(tenant_id,role_id,permission_id) do nothing;
