create table qms_inspection_standard (
 id bigint generated by default as identity primary key,tenant_id bigint not null,org_id bigint not null,
 standard_no varchar(64) not null,part_id bigint not null,drawing_revision_id bigint not null,document_version int not null default 1,
 status varchar(32) not null default 'AI_GENERATED',source_type varchar(32) not null default 'RULE',reaction_plan varchar(2000),
 created_by bigint,created_at timestamp not null default current_timestamp,updated_by bigint,updated_at timestamp not null default current_timestamp,deleted boolean not null default false,version int not null default 0,
 unique(tenant_id,id),unique(tenant_id,drawing_revision_id,document_version),foreign key(tenant_id,part_id) references qms_part(tenant_id,id),foreign key(tenant_id,drawing_revision_id) references qms_drawing_revision(tenant_id,id));
create table qms_inspection_standard_item (
 id bigint generated by default as identity primary key,tenant_id bigint not null,org_id bigint not null,inspection_standard_id bigint not null,sequence_no int not null,
 category varchar(32) not null,item_name varchar(255) not null,requirement varchar(1000),characteristic_id bigint not null,nominal_value numeric(18,6),lower_limit numeric(18,6),upper_limit numeric(18,6),special_characteristic_code varchar(64),
 supplier_batch_sampling varchar(255),supplier_batch_method varchar(255),supplier_annual_sampling varchar(255),supplier_annual_method varchar(255),remark varchar(1000),source_type varchar(32) not null default 'RULE',evidence_id bigint,confidence numeric(5,4),review_status varchar(32) not null default 'PENDING',
 created_by bigint,created_at timestamp not null default current_timestamp,updated_by bigint,updated_at timestamp not null default current_timestamp,deleted boolean not null default false,version int not null default 0,
 unique(tenant_id,id),unique(tenant_id,inspection_standard_id,sequence_no),foreign key(tenant_id,inspection_standard_id) references qms_inspection_standard(tenant_id,id),foreign key(tenant_id,characteristic_id) references qms_quality_characteristic(tenant_id,id));
insert into sys_permission(tenant_id,permission_code,permission_name,resource_type,module_code,action_code,created_by,updated_by,deleted,version)
select t.id,'qms:inspection-standard:edit','Edit inspection standard drafts','API','qms','edit',0,0,false,0 from sys_tenant t where t.deleted=false and not exists(select 1 from sys_permission p where p.tenant_id=t.id and p.permission_code='qms:inspection-standard:edit' and p.deleted=false);
insert into sys_role_permission(tenant_id,role_id,permission_id,created_by,updated_by,deleted,version)
select r.tenant_id,r.id,p.id,0,0,false,0 from sys_role r join sys_permission p on p.tenant_id=r.tenant_id where r.role_code='platform_admin' and r.deleted=false and p.permission_code='qms:inspection-standard:edit' and p.deleted=false on conflict(tenant_id,role_id,permission_id) do nothing;
