create table sys_user_org (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    user_id bigint not null,
    org_id bigint not null,
    is_primary boolean not null default false,
    scope_weight int not null default 0,
    valid_from timestamp,
    valid_to timestamp,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb
);

create index idx_sys_user_org_tenant_user on sys_user_org (tenant_id, user_id);
create index idx_sys_user_org_tenant_org on sys_user_org (tenant_id, org_id);
create unique index uk_sys_user_org_active
    on sys_user_org (tenant_id, user_id, org_id)
    where deleted = false;
create unique index uk_sys_user_org_primary
    on sys_user_org (tenant_id, user_id)
    where is_primary = true and deleted = false;

insert into sys_user_org
    (tenant_id, user_id, org_id, is_primary, scope_weight,
     created_by, created_at, updated_by, updated_at, deleted, version)
select u.tenant_id, u.id, u.primary_org_id, true, 100,
       u.created_by, current_timestamp, u.updated_by, current_timestamp, false, 0
  from sys_user u
 where u.primary_org_id is not null
   and u.deleted = false
on conflict do nothing;
