create table sys_theme_config (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    config_key varchar(64) not null,
    theme_name varchar(64) not null,
    primary_color varchar(32) not null,
    sidebar_mode varchar(32) not null,
    tokens_json jsonb not null default '{}'::jsonb,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_theme_config_key unique (tenant_id, config_key)
);

create table sys_brand_config (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    config_key varchar(64) not null,
    brand_name varchar(128) not null,
    logo_url varchar(512),
    favicon_url varchar(512),
    login_hero_title varchar(256) not null,
    login_hero_subtitle text not null,
    login_ops_title varchar(256) not null,
    login_ops_description text not null,
    login_background_type varchar(32) not null,
    login_background_image_url varchar(512),
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_brand_config_key unique (tenant_id, config_key)
);

create table sys_i18n_resource (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    locale varchar(32) not null,
    resource_key varchar(256) not null,
    resource_value text not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_i18n_resource_key unique (tenant_id, locale, resource_key)
);

create table sys_user_experience_preference (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    user_id bigint not null,
    preference_json jsonb not null default '{}'::jsonb,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_user_experience_preference unique (tenant_id, user_id)
);

create index idx_sys_i18n_resource_locale on sys_i18n_resource (tenant_id, locale);
create index idx_sys_user_experience_preference_user on sys_user_experience_preference (tenant_id, user_id);

insert into sys_theme_config (
    tenant_id, config_key, theme_name, primary_color, sidebar_mode, tokens_json, created_by, updated_by
) values (
    1, 'current', 'light-industrial', '#334155', 'dark', '{}'::jsonb, 1, 1
) on conflict (tenant_id, config_key) do nothing;

insert into sys_brand_config (
    tenant_id, config_key, brand_name, login_hero_title, login_hero_subtitle,
    login_ops_title, login_ops_description, login_background_type, created_by, updated_by
) values (
    1,
    'current',
    'IAF 平台',
    '面向制造企业的工业应用基础平台',
    '统一平台管理、权限、组织、审批、集成和业务扩展能力，为 WMS、MES、SRM、QMS 等工业系统提供一致工程底座。',
    '工业运营视图',
    '主题、权限和复杂视图能力从平台层统一治理，支撑管理端、Kanban、设计器和大屏场景。',
    'token',
    1,
    1
) on conflict (tenant_id, config_key) do nothing;

insert into sys_i18n_resource (tenant_id, locale, resource_key, resource_value, created_by, updated_by)
values
    (1, 'zh-CN', 'app.name', 'IAF 平台', 1, 1),
    (1, 'en-US', 'app.name', 'IAF Platform', 1, 1)
on conflict (tenant_id, locale, resource_key) do nothing;

insert into sys_permission (tenant_id, permission_code, permission_name, resource_type, module_code, action_code)
values
    (1, 'platform:theme:view', 'View platform theme configuration', 'API', 'platform', 'theme:view'),
    (1, 'platform:theme:update', 'Update platform theme configuration', 'API', 'platform', 'theme:update'),
    (1, 'platform:brand:view', 'View platform brand configuration', 'API', 'platform', 'brand:view'),
    (1, 'platform:brand:update', 'Update platform brand configuration', 'API', 'platform', 'brand:update'),
    (1, 'platform:i18n:view', 'View platform i18n resources', 'API', 'platform', 'i18n:view'),
    (1, 'platform:i18n:update', 'Update platform i18n resources', 'API', 'platform', 'i18n:update'),
    (1, 'platform:preference:me', 'Manage own experience preferences', 'API', 'platform', 'preference:me')
on conflict (tenant_id, permission_code) do nothing;

insert into sys_role_permission (tenant_id, role_id, permission_id, created_by, updated_by)
select 1, 1, p.id, 1, 1
  from sys_permission p
 where p.tenant_id = 1
   and p.permission_code in (
       'platform:theme:view',
       'platform:theme:update',
       'platform:brand:view',
       'platform:brand:update',
       'platform:i18n:view',
       'platform:i18n:update',
       'platform:preference:me'
   )
on conflict (tenant_id, role_id, permission_id) do nothing;
