create table sys_tenant (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    tenant_code varchar(64) not null,
    tenant_name varchar(128) not null,
    status varchar(32) not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_tenant_code unique (tenant_code)
);

create table sys_user (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    username varchar(64) not null,
    display_name varchar(128) not null,
    mobile varchar(32),
    email varchar(128),
    password_hash varchar(255) not null,
    status varchar(32) not null,
    primary_org_id bigint,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_user_tenant_username unique (tenant_id, username)
);

create table sys_org (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    parent_id bigint,
    org_code varchar(64) not null,
    org_name varchar(128) not null,
    org_type varchar(32) not null,
    status varchar(32) not null,
    sort_no int not null default 0,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_org_tenant_code unique (tenant_id, org_code)
);

create table sys_role (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    role_code varchar(64) not null,
    role_name varchar(128) not null,
    role_type varchar(32) not null,
    status varchar(32) not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_role_tenant_code unique (tenant_id, role_code)
);

create table sys_permission (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    permission_code varchar(128) not null,
    permission_name varchar(128) not null,
    resource_type varchar(32) not null,
    module_code varchar(64) not null,
    action_code varchar(64) not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_permission_tenant_code unique (tenant_id, permission_code)
);

create table sys_user_role (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    user_id bigint not null,
    role_id bigint not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_user_role unique (tenant_id, user_id, role_id)
);

create table sys_role_permission (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    role_id bigint not null,
    permission_id bigint not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_role_permission unique (tenant_id, role_id, permission_id)
);

create index idx_sys_user_tenant_status on sys_user (tenant_id, status);
create index idx_sys_org_tenant_parent on sys_org (tenant_id, parent_id);
create index idx_sys_role_tenant_status on sys_role (tenant_id, status);
create index idx_sys_permission_tenant_module on sys_permission (tenant_id, module_code);

insert into sys_tenant (id, tenant_id, tenant_code, tenant_name, status)
values (1, 1, 'default', 'Default Tenant', 'ENABLED');

insert into sys_user (id, tenant_id, username, display_name, password_hash, status)
values (1, 1, 'admin', 'Platform Administrator', '{noop}admin123', 'ENABLED');

insert into sys_role (id, tenant_id, role_code, role_name, role_type, status)
values (1, 1, 'platform_admin', 'Platform Administrator', 'INTERNAL', 'ENABLED');

insert into sys_permission (id, tenant_id, permission_code, permission_name, resource_type, module_code, action_code)
values (1, 1, 'platform:auth:me', 'View current user', 'API', 'platform', 'me');

insert into sys_user_role (tenant_id, user_id, role_id)
values (1, 1, 1);

insert into sys_role_permission (tenant_id, role_id, permission_id)
values (1, 1, 1);
