alter table sys_tenant
    add column if not exists disabled_at timestamp,
    add column if not exists initialization_status varchar(32) not null default 'COMPLETED',
    add column if not exists initialization_error varchar(512);

create table sys_tenant_quota (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    quota_key varchar(64) not null,
    quota_limit bigint not null,
    quota_used bigint not null default 0,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_tenant_quota_key unique (tenant_id, quota_key)
);

create index idx_sys_tenant_quota_tenant on sys_tenant_quota (tenant_id);

create table platform_outbox_event (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    event_id varchar(64) not null,
    aggregate_type varchar(128) not null,
    aggregate_id varchar(128) not null,
    event_type varchar(128) not null,
    payload_json jsonb not null,
    status varchar(32) not null,
    retry_count int not null default 0,
    next_retry_at timestamp,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_platform_outbox_event_id unique (event_id)
);

create index idx_platform_outbox_tenant_status on platform_outbox_event (tenant_id, status);
create index idx_platform_outbox_event_status on platform_outbox_event (tenant_id, event_type, status);
create index idx_platform_outbox_aggregate on platform_outbox_event (tenant_id, aggregate_type, aggregate_id);

insert into sys_permission (tenant_id, permission_code, permission_name, resource_type, module_code, action_code)
values
    (1, 'platform:tenant:view', 'View tenants', 'API', 'platform', 'view'),
    (1, 'platform:tenant:create', 'Create tenant', 'API', 'platform', 'create'),
    (1, 'platform:tenant:update', 'Update tenant', 'API', 'platform', 'update'),
    (1, 'platform:tenant:disable', 'Disable tenant', 'API', 'platform', 'disable'),
    (1, 'platform:tenant:enable', 'Enable tenant', 'API', 'platform', 'enable'),
    (1, 'platform:tenant-quota:view', 'View tenant quota', 'API', 'platform', 'view'),
    (1, 'platform:tenant-quota:update', 'Update tenant quota', 'API', 'platform', 'update'),
    (1, 'platform:outbox:view', 'View outbox events', 'API', 'platform', 'view'),
    (1, 'platform:outbox:retry', 'Retry outbox events', 'API', 'platform', 'retry')
on conflict (tenant_id, permission_code) do nothing;

insert into sys_role_permission (tenant_id, role_id, permission_id)
select 1, r.id, p.id
  from sys_role r
  join sys_permission p on p.tenant_id = r.tenant_id
 where r.tenant_id = 1
   and r.role_code = 'platform_admin'
   and p.permission_code in (
       'platform:tenant:view',
       'platform:tenant:create',
       'platform:tenant:update',
       'platform:tenant:disable',
       'platform:tenant:enable',
       'platform:tenant-quota:view',
       'platform:tenant-quota:update',
       'platform:outbox:view',
       'platform:outbox:retry'
   )
on conflict (tenant_id, role_id, permission_id) do nothing;

insert into sys_tenant_quota (tenant_id, quota_key, quota_limit, quota_used, created_by, updated_by)
values (1, 'USER_COUNT', 1000, 1, 1, 1)
on conflict (tenant_id, quota_key) do nothing;
