create table sys_menu (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    parent_id bigint,
    menu_code varchar(128) not null,
    menu_type varchar(32) not null,
    title_key varchar(256) not null,
    route_path varchar(256),
    component_key varchar(256),
    icon varchar(64),
    sort_no int not null default 0,
    visible boolean not null default true,
    enabled boolean not null default true,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_menu_tenant_code unique (tenant_id, menu_code)
);

create table sys_menu_permission (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    menu_id bigint not null,
    permission_id bigint not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_menu_permission unique (tenant_id, menu_id, permission_id)
);

create table sys_role_menu (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    role_id bigint not null,
    menu_id bigint not null,
    created_by bigint,
    created_at timestamp not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp not null default current_timestamp,
    deleted boolean not null default false,
    version int not null default 0,
    ext_json jsonb,
    constraint uk_sys_role_menu unique (tenant_id, role_id, menu_id)
);

create index idx_sys_menu_parent on sys_menu (tenant_id, parent_id);
create index idx_sys_menu_visible on sys_menu (tenant_id, visible, enabled);
create index idx_sys_role_menu_role on sys_role_menu (tenant_id, role_id);

insert into sys_permission (tenant_id, permission_code, permission_name, resource_type, module_code, action_code, created_by, updated_by)
values
    (1, 'platform:menu:view', 'View platform menus', 'API', 'platform', 'menu:view', 1, 1),
    (1, 'platform:menu:create', 'Create platform menu', 'API', 'platform', 'menu:create', 1, 1),
    (1, 'platform:menu:update', 'Update platform menu', 'API', 'platform', 'menu:update', 1, 1),
    (1, 'platform:menu:disable', 'Disable platform menu', 'API', 'platform', 'menu:disable', 1, 1),
    (1, 'platform:permission:view', 'View platform permissions', 'API', 'platform', 'permission:view', 1, 1),
    (1, 'platform:role:assign-menu', 'Assign menus to role', 'API', 'platform', 'role:assign-menu', 1, 1)
on conflict (tenant_id, permission_code) do nothing;

insert into sys_role_permission (tenant_id, role_id, permission_id, created_by, updated_by)
select 1, 1, p.id, 1, 1
  from sys_permission p
 where p.tenant_id = 1
   and p.permission_code in (
       'platform:menu:view',
       'platform:menu:create',
       'platform:menu:update',
       'platform:menu:disable',
       'platform:permission:view',
       'platform:role:assign-menu'
   )
on conflict (tenant_id, role_id, permission_id) do nothing;

insert into sys_menu (
    tenant_id, parent_id, menu_code, menu_type, title_key, route_path,
    component_key, icon, sort_no, visible, enabled, created_by, updated_by
) values
    (1, null, 'platform', 'GROUP', 'menu.platform', null, null, 'AppstoreOutlined', 100, true, true, 1, 1)
on conflict (tenant_id, menu_code) do nothing;

insert into sys_menu (
    tenant_id, parent_id, menu_code, menu_type, title_key, route_path,
    component_key, icon, sort_no, visible, enabled, created_by, updated_by
) values
    (1, (select id from sys_menu where tenant_id = 1 and menu_code = 'platform'), 'platform.users', 'MENU', 'menu.users', '/platform/users', 'platform/users/UserListPage', 'UserOutlined', 110, true, true, 1, 1),
    (1, (select id from sys_menu where tenant_id = 1 and menu_code = 'platform'), 'platform.orgs', 'MENU', 'menu.orgs', '/platform/orgs', 'platform/orgs/OrgTreePage', 'TeamOutlined', 120, true, true, 1, 1),
    (1, (select id from sys_menu where tenant_id = 1 and menu_code = 'platform'), 'platform.roles', 'MENU', 'menu.roles', '/platform/roles', 'platform/roles/RoleListPage', 'SettingOutlined', 130, true, true, 1, 1),
    (1, (select id from sys_menu where tenant_id = 1 and menu_code = 'platform'), 'platform.menus', 'MENU', 'menu.menus', '/platform/menus', 'platform/menus/PlatformMenuConsolePage', 'MenuOutlined', 140, true, true, 1, 1),
    (1, (select id from sys_menu where tenant_id = 1 and menu_code = 'platform'), 'platform.dictionaries', 'MENU', 'menu.dictionaries', '/platform/dictionaries', 'platform/config/PlatformDictionaryParameterPage', 'DatabaseOutlined', 150, true, true, 1, 1),
    (1, (select id from sys_menu where tenant_id = 1 and menu_code = 'platform'), 'platform.auditLogs', 'MENU', 'menu.auditLogs', '/platform/audit-logs', 'platform/config/PlatformAuditLogPage', 'AuditOutlined', 160, true, true, 1, 1),
    (1, (select id from sys_menu where tenant_id = 1 and menu_code = 'platform'), 'platform.approvalTasks', 'MENU', 'menu.approvalTasks', '/platform/approval/tasks', 'platform/approval/ApprovalTaskCenterPage', 'AuditOutlined', 170, true, true, 1, 1),
    (1, (select id from sys_menu where tenant_id = 1 and menu_code = 'platform'), 'platform.kanban', 'MENU', 'menu.kanban', '/platform/kanban', 'platform/kanban/PlatformKanbanPage', 'DashboardOutlined', 180, true, true, 1, 1)
on conflict (tenant_id, menu_code) do nothing;

insert into sys_menu_permission (tenant_id, menu_id, permission_id, created_by, updated_by)
select 1, m.id, p.id, 1, 1
  from (values
      ('platform.users', 'platform:user:view'),
      ('platform.orgs', 'platform:org:view'),
      ('platform.roles', 'platform:role:view'),
      ('platform.menus', 'platform:menu:view')
  ) as mp(menu_code, permission_code)
  join sys_menu m on m.tenant_id = 1 and m.menu_code = mp.menu_code
  join sys_permission p on p.tenant_id = 1 and p.permission_code = mp.permission_code
on conflict (tenant_id, menu_id, permission_id) do nothing;

insert into sys_role_menu (tenant_id, role_id, menu_id, created_by, updated_by)
select 1, 1, m.id, 1, 1
  from sys_menu m
 where m.tenant_id = 1
on conflict (tenant_id, role_id, menu_id) do nothing;
